# Generated by Django 2.2.10 on 2020-03-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="formpage",
            name="redirect_to",
            field=models.URLField(
                blank=True,
                help_text="Entering a URL here will prevent the page from being visited, and will instead redirect the user.",
                verbose_name="Redirect to external URL",
            ),
        ),
    ]
