# Generated by Django 2.2.10 on 2020-03-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0002_formpage_redirect_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("singleline", "Single line text"),
                    ("multiline", "Multi-line text"),
                    ("email", "Email"),
                    ("number", "Number"),
                    ("url", "URL"),
                    ("checkbox", "Checkbox"),
                    ("checkboxes", "Checkboxes"),
                    ("dropdown", "Drop down"),
                    ("multiselect", "Multiple select"),
                    ("radio", "Radio buttons"),
                    ("date", "Date"),
                    ("datetime", "Date/time"),
                    ("hidden", "Hidden field"),
                    ("heading", "Heading"),
                    ("subheading", "Subheading"),
                ],
                max_length=16,
                verbose_name="field type",
            ),
        ),
    ]
