# Generated by Django 2.2.10 on 2020-03-20 16:39

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0002_formpage_redirect_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="formfield",
            name="additional_text",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Rich text to display before the form field"
            ),
        ),
    ]
