# Generated by Django 4.2.19 on 2025-02-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("forms", "0009_required_listing_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormSubmissionAccessControl",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "groups_with_access",
                    models.ManyToManyField(
                        help_text="The group(s) that can see form submissions",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form submission access control",
            },
        ),
    ]
