# Generated by Django 4.2.19 on 2025-02-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailforms", "0005_alter_formsubmission_form_data"),
        ("forms", "0010_formsubmissionaccesscontrol"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormSubmission",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("wagtailforms.formsubmission",),
        ),
        migrations.AddField(
            model_name="formpage",
            name="auto_delete",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "Don't delete submissions"),
                    (7, "One week"),
                    (30, "One month"),
                    (90, "Three months"),
                ],
                default=0,
                help_text="Delete submissions automatically after this amount of time",
            ),
        ),
    ]
