# vim:set sw=2 ts=2 et:
# This is a sample .gitlab-ci.yml created by wagtail-kit.  You should review
# it for any necessary changes.

# Stages are groups that jobs can be groupped into.
# Jobs within each stage run in parallel and if one of them fails, the next
# stage won't be run.
# This will set up the following:
#
# - Build stage: build of static assets.
# - Test stage: code style, migration, basic configuration checks and unit
#   tests.
# - Deploy stage: deploy to Heroku.
stages:
  - build
  - test
  - deploy_site
  - pages
  - copy

.cache_static:
  cache:
    key:
      files:
        - package-lock.json
        - bc/static_src
    paths:
      - ./node_modules
      - ./bc/static_compiled
    policy: pull

.node:
  image: node:12.22.12-alpine
  extends: .cache_static
  needs:
    - static

# Test if static assets can be built succesfully.
static:
  extends: .node
  needs: []
  stage: build
  before_script:
    - apk add --no-cache rsync
  script:
    - npm ci --no-optional --no-audit --progress=false
    - npm run build:prod
  cache:
    # Here only we want to write to the cache.
    policy: pull-push

poetry:
  # If you update the python image version here, make sure you update all jobs that depend on this
  # and the version in the Dockerfile and provision scripts as well
  image: python:3.8-bullseye
  stage: build
  variables:
    POETRY_VERSION: 1.8.3
  script:
    - pip install poetry==$POETRY_VERSION
    - python -m venv venv
    - source venv/bin/activate
    - pip install -U pip setuptools wheel
    - poetry install
  artifacts:
    name: 'poetry-$CI_JOB_ID'
    paths:
      - ./venv/
    expire_in: 30 mins

# Check python code style.
flake8:
  image: python:3.8-bullseye
  stage: test
  dependencies:
    - poetry
  before_script:
    - source venv/bin/activate
  script:
    - flake8 bc

# Check imports sort order, i.e. check whether they are in an alphabetical
# order and grouped properly.
isort:
  image: python:3.8-bullseye
  stage: test
  dependencies:
    - poetry
  before_script:
    - source venv/bin/activate
  script:
    - isort --check-only --diff --recursive bc

lint_js:
  extends: .node
  stage: test
  script:
    - npm run lint:js

lint_css:
  extends: .node
  stage: test
  script:
    - npm run lint:css

lint_format:
  extends: .node
  stage: test
  script:
    - npm run lint:format

# Run black and check for changes
black:
  image: python:3.8-bullseye
  stage: test
  dependencies:
    - poetry
  before_script:
    - source venv/bin/activate
  script:
    - black --check ./

# Check settings, migrations and run tests.
test_python:
  # Make sure this Python version matches the version in your Dockerfile.
  image: python:3.8-bullseye
  extends: .cache_static
  stage: test
  needs:
    - static
    - poetry
  services:
    # Make sure this matches the Postgres version you run on your servers.
    - postgres:13.10
  variables:
    # Run tests with the production settings.
    DJANGO_SETTINGS_MODULE: bc.settings.production

    # SECRET_KEY is required by Django to start.
    SECRET_KEY: fake_secret_key_to_run_tests

    # Silence RECAPTCHA
    RECAPTCHA_PUBLIC_KEY: 'dummy-key-value'
    RECAPTCHA_PRIVATE_KEY: 'dummy-key-value'

    # Some settings are used in constants
    RESPOND_COMPLAINTS_WEBSERVICE: 'TestCreateComplaints'
    RESPOND_FOI_WEBSERVICE: 'TestCreateFOI'
    RESPOND_SAR_WEBSERVICE: 'TestCreateSAR'
    RESPOND_COMMENTS_WEBSERVICE: 'TestCreateComments'
    RESPOND_COMPLIMENTS_WEBSERVICE: 'TestCreateCompliments'
    RESPOND_DISCLOSURES_WEBSERVICE: 'TestCreateDisclosures'

    # Postgres credentials
    POSTGRES_USER: db_user
    POSTGRES_PASSWORD: db_pass # pragma: allowlist secret

    # This is the URL used by databases on our CI.
    DATABASE_URL: postgres://db_user:db_pass@postgres/postgres # pragma: allowlist secret

    # Don't redirect to HTTPS in tests.
    SECURE_SSL_REDIRECT: 'false'

    # Don't run birdbath in tests.
    BIRDBATH_REQUIRED: 'false'
  before_script:
    - source venv/bin/activate
  script:
    # We need to run the collectstatic command, because we use ManifestStaticFilesStorage.
    # Otherwise the check command will fail
    - python manage.py collectstatic --verbosity 0 --noinput --clear

    # Run system checks
    - python manage.py check

    # Check for missing migrations
    - python manage.py makemigrations --check --noinput

    # Create cache table.
    - python manage.py createcachetable

    # Run back-end tests
    - python manage.py test

test_js:
  extends: .node
  stage: test
  script:
    # Run front-end tests
    - npm run test:coverage

.heroku_deployment_template: &heroku_deployment_template
  image: curlimages/curl:latest
  stage: deploy_site
  script:
    - 'echo "Deploying to Heroku. To see progress, go to: https://dashboard.heroku.com/apps/$HEROKU_APP/activity"'
    - curl --fail-with-body -s -X POST -m 900 https://heroku-deploy.torchbox.com/$HEROKU_APP/$CI_COMMIT_SHA?key=$DEPLOYMENT_KEY

# Deploy to the staging server.
deploy_staging:
  # We use Debian image because Heroku has a lot of dependencies and is well
  # supported on Debian based distributions.
  image: debian:bullseye
  stage: deploy_site
  variables:
    # Your app's name.
    #   $ heroku apps - t torchbox
    HEROKU_APP: buckinghamshire-staging
  only:
    - staging
  <<: *heroku_deployment_template

# Deploy to the production site.
deploy_production:
  # We use Debian image because Heroku has a lot of dependencies and is well
  # supported on Debian based distributions.
  image: debian:bullseye
  stage: deploy_site
  variables:
    # Your app's name.
    #   $ heroku apps - t torchbox
    HEROKU_APP: buckinghamshire-production
  only:
    - master
  when: manual
  <<: *heroku_deployment_template

# Deploy to the content prep site.
deploy_content_prep:
  # We use Debian image because Heroku has a lot of dependencies and is well
  # supported on Debian based distributions.
  image: debian:bullseye
  stage: deploy_site
  variables:
    # Your app's name.
    #   $ heroku apps - t torchbox
    HEROKU_APP: buckinghamshire-content-prep
  only:
    - master
  when: manual
  <<: *heroku_deployment_template

pages:
  image: python:3.8
  stage: pages
  only:
    - master
  dependencies:
    - poetry
  before_script:
    - source venv/bin/activate
  script:
    # Include CHANGELOG in the docs
    - cp CHANGELOG.md docs/changelog.md
    - mkdocs build
    # Clear out the public/ folder before moving the built docs site there.
    # We're also using public/ for WHITENOISE_ROOT, so this this prevents us
    # inadvertently deploying robots.txt etc. to Gitlab Pages.
    - rm -rf public/*
    - mv site/* public
  artifacts:
    paths:
      - public

# Sync data and media from production to staging
# requires FLIGHTPATH_* keys below to be added to repository secrets
# https://git.torchbox.com/sysadmin/flightpath#app-copy
copy_prod_to_staging:
  stage: copy
  when: manual
  only:
    - staging
  variables:
    SOURCE_APP: buckinghamshire-production
    DESTINATION_APP: buckinghamshire-staging
    SOURCE_KEY: $FLIGHTPATH_SOURCE_KEY
    DESTINATION_KEY: $FLIGHTPATH_DESTINATION_KEY
    AUTH_KEY: $FLIGHTPATH_AUTH_KEY
  before_script:
    - apt-get update -y
    - apt-get install -y curl jq
  script:
    - >
      export JOB_STATUS=$(curl -f -X POST -m 900
      -H "Authorization: Token $AUTH_KEY" -d "source_key=$SOURCE_KEY&destination_key=$DESTINATION_KEY&copy_media=1&from_backup=1"
      "https://flightpath.torchbox.com/copy/$SOURCE_APP/$DESTINATION_APP/")
    - echo $JOB_STATUS
    - export JOB_ID=$(echo $JOB_STATUS | jq -r '.job_id')
    - echo $JOB_ID
