default_language_version:
  node: system
  python: python3.11

repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
  - repo: https://github.com/python/black
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
  - repo: https://github.com/adamchainz/django-upgrade
    rev: '1.16.0' # replace with latest tag on GitHub
    hooks:
      - id: django-upgrade
        args: [--target-version, '4.2'] # Replace with Django version
  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.2' # keep version in sync with version installed in the Dockerfile
    hooks:
      - id: poetry-check
      - id: poetry-lock
        # Never update dependencies and only run on changes to pyproject.toml
        args: [--no-update]
        files: ^pyproject.toml$
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v6.5.1
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@6.5.1
          - eslint-config-airbnb@18.0.1
          - eslint-config-prettier@6.4.0
          - eslint-config-torchbox@0.3.1
          - eslint-plugin-import@2.18.2
          - eslint-plugin-jsx-a11y@6.2.3
          - eslint-plugin-react@7.16.0
          - eslint-plugin-react-hooks@1.7.0
          - '@babel/core@7.5.0'
          - '@babel/preset-env@7.5.0'
          - '@babel/preset-react@7.0.0'
          - babel-eslint@10.0.2
  - repo: https://github.com/prettier/prettier
    rev: 1.18.2
    hooks:
      - id: prettier
  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: c4c991cd38b0218735858716b09924f8b20e3812
    hooks:
      - id: stylelint
        additional_dependencies:
          - stylelint@10.1.0
          - stylelint-config-torchbox@0.5.0
  - repo: git@github.com:Yelp/detect-secrets
    rev: v0.13.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: >
          (?x)^(
              .*/tests/.*|
              package-lock.json|
              poetry.lock
          )$
  - repo: https://github.com/adamchainz/django-upgrade
    rev: '1.19.0' # replace with latest tag on GitHub
    hooks:
      - id: django-upgrade
        args: [--target-version, '4.2'] # Replace with Django version
