default_language_version:
  node: system
  python: python3.11

repos:
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
  - repo: https://github.com/python/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/adamchainz/django-upgrade
    rev: '1.25.0' # replace with latest tag on GitHub
    hooks:
      - id: django-upgrade
        args: [--target-version, '4.2'] # Replace with Django version
  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.5' # keep version in sync with version installed in the Dockerfile
    hooks:
      - id: poetry-check
      - id: poetry-lock
        # Never update dependencies and only run on changes to pyproject.toml
        args: [--no-update]
        files: ^pyproject.toml$
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.33.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@9.33.0
          - eslint-config-airbnb@19.0.4
          - eslint-config-prettier@10.1.8
          - eslint-config-torchbox@1.1.0
          - eslint-plugin-import@2.32.0
          - eslint-plugin-jsx-a11y@6.10.2
          - eslint-plugin-react@7.37.5
          - eslint-plugin-react-hooks@5.2.0
          - '@babel/core@7.28.0'
          - '@babel/preset-env@7.28.0'
          - '@babel/preset-react@7.27.1'
          - '@babel/eslint-parser@7.28.0'
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: c4c991cd38b0218735858716b09924f8b20e3812 # pragma: allowlist secret
    hooks:
      - id: stylelint
        additional_dependencies:
          - stylelint@15.10.2
          - stylelint-config-torchbox@3.0.0
  - repo: git@github.com:Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: >
          (?x)^(
              .*/tests/.*|
              package-lock.json|
              poetry.lock
          )$
