site_name: Buckinghamshire Council
repo_url: https://git.torchbox.com/buckinghamshire-council/bc
site_url:
edit_uri: 'edit/master/docs/'

repo_name: Gitlab
dev_addr: 0.0.0.0:8001
theme:
  name: material
  font: false
markdown_extensions:
  - codehilite
  - admonition
  - sane_lists
  - toc:
      permalink: true
  # pymdown-extensions meant to bring the Markdown implementation closer to GFM.
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - 'Home': 'index.md'
  - 'Infrastructure': 'infrastructure.md'
  - 'Project conventions': 'project_conventions.md'
  - 'Deployment': 'deployment.md'
  - 'Front end tooling': 'front-end-tooling.md'
  - 'Continuous integration': 'continuous-integration.md'
  - 'Anonymised data': 'anonymised_data.md'
  - 'Data protection': 'data_protection.md'
  - 'CHANGELOG': 'CHANGELOG.md'
