site_name: Buckinghamshire Council
repo_url: https://github.com/Buckinghamshire-Digital-Service/buckinghamshire-council/
site_url: https://Buckinghamshire-Digital-Service.github.io/buckinghamshire-council/
edit_uri: 'edit/master/docs/'

repo_name: GitHub
dev_addr: 0.0.0.0:8001
theme:
  name: material
  font: false
markdown_extensions:
  - codehilite
  - admonition
  - sane_lists
  - toc:
      permalink: true
  # pymdown-extensions meant to bring the Markdown implementation closer to GFM.
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - 'Home': 'index.md'
  - 'Project conventions': 'project-conventions.md'
  - 'Front end tooling': 'front-end-tooling.md'
  - 'Hosting': 'hosting.md'
  - 'Infrastructure': 'infrastructure.md'
  - 'Email and SMS': 'email-and-sms.md'
  - 'Continuous integration': 'continuous-integration.md'
  - 'Continuous deployment': 'continuous-deployment.md'
  - 'Data and Privacy':
      - 'Anonymised data': 'anonymised-data.md'
      - 'Data protection': 'data-protection.md'
      - 'Cookies': 'cookies.md'
  - 'External Integrations':
      - 'Recruitment site': 'recruitment-site.md'
      - 'Complaints and requests': 'complaints-and-requests.md'
      - 'Live chat client': 'live-chat-client.md'
      - 'Postcode lookup': 'postcode-lookup.md'
  - 'Contributing': 'contributing.md'
  - 'CHANGELOG': 'CHANGELOG.md'
