[tool.poetry]
name = "bc"
version = "0.1.0"
description = "Buckinghamshire Council Website"
authors = ["Torchbox <hello@torchbox.com>"]

[tool.poetry.dependencies]
python = "~3.8"
bleach = "3.1.0"
dj-database-url = "0.5.0"
Django = "~3.2"
django-basic-auth-ip-whitelist = "^0.3.4"
django-birdbath = "^1.0.0"
django-csp = "3.7"
django-gov-notify = "^0.3.0"
django-pattern-library = "0.5"
django-redis = "4.11.0"
django-referrer-policy = "1.0"
django-storages = {version = "1.9.1", extras = ["boto3"]}
elasticsearch = "7.9.0"
factory-boy = "3.2.1"
freezegun = "1.1.0"
gunicorn = {version = "19.9.0", optional = true}
psycopg2 = "^2.9.7"
PyJWT = "2.0.0"
redis = "2.10.6"
scout-apm = "2.0.2"
tabulate = "0.8.7"
urllib3 = "1.26.11"
wagtail = "~5.2"
wagtail-django-recaptcha = {git = "https://github.com/torchbox-forks/wagtail-django-recaptcha", tag = "2.1.1+tbx"}
wagtail-factories = "^4.1.0"
wagtail-orderable = "^1.2.0"
wagtail-transfer = "^0.9.3"
wagtailgeowidget = "8.1.1"
whitenoise = "5.0"
zeep = "3.4.0"
sentry-sdk = "^1.19.1"
backoff = "^2.2.1"
responses = "0.16.0"
django-filter = "^23.5"
wagtail-modeladmin = "^1.0.0"

[tool.poetry.extras]
gunicorn = ["gunicorn"]

[tool.poetry.dev-dependencies]
# Docs dependencies
mkdocs = "1.3.0"
mkdocs-material = "8.2.8"
pymdown-extensions = "9.3"

# Linting
black = "22.3.0"
detect-secrets = "0.13.0"
flake8 = "3.7.7"
isort = "4.3.18"
seed-isort-config = "1.9.0"

# Database snapshots
DSLR = "0.2.0"
stellar = "0.4.5"

# Pinned for stellar 0.4.5
SQLAlchemy = "1.2.5"
SQLAlchemy-Utils = "0.33.1"

# Development dependencies
django-extensions = "2.1.6"
honcho = "^1.1.0"
pre-commit = "1.16.1"
Werkzeug = "0.14.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
