[tool.poetry]
name = "bc"
version = "0.1.0"
description = "Buckinghamshire Council Website"
authors = ["Torchbox <hello@torchbox.com>"]

[tool.poetry.dependencies]
python = "~3.11"
bleach = "~6.1.0"
dj-database-url = "~2.1"
Django = "~4.2"
django-basic-auth-ip-whitelist = "^0.5"
django-birdbath = "^1.1.1"
django-csp = "~3.8"
django-gov-notify = "^0.4.0"
django-pattern-library = "~1.2.0"
django-redis = "~5.4.0"
django-referrer-policy = "1.0"
django-storages = {version = "1.14.2", extras = ["boto3"]}
elasticsearch = "7.9.0"
factory-boy = "~3.3"
freezegun = "~1.4"
gunicorn = {version = "~21.2.0", optional = true}
psycopg2 = "~2.9"
PyJWT = "~2.8"
scout-apm = "~3.1"
tabulate = "0.9.0"
urllib3 = "~2.2"
wagtail = "~5.2"
wagtail-django-recaptcha = {git = "https://github.com/torchbox-forks/wagtail-django-recaptcha", tag = "2.1.1+tbx"}
wagtail-factories = "^4.1.0"
wagtail-orderable = "^1.2.0"
wagtail-transfer = "^0.9"
wagtailgeowidget = "8.1.1"
whitenoise = "~6.6"
zeep = "~4.2"
sentry-sdk = "~1.40.5"
backoff = "^2.2.1"
responses = "~0.25"
django-filter = "^23.5"
wagtail-modeladmin = "^1.0.0"
django-upgrade = "^1.16.0"

[tool.poetry.extras]
gunicorn = ["gunicorn"]

[tool.poetry.group.dev.dependencies]
# Docs dependencies
mkdocs = "1.5.3"
mkdocs-material = "8.2.8"
pymdown-extensions = "10.7.1"

# Linting
black = "24.4.0"
detect-secrets = "1.4.0"
flake8 = "7.0.0"
isort = "5.13.2"
seed-isort-config = "2.2.0"

# Development dependencies
django-extensions = "~3.2"
honcho = "^1.1.0"
pre-commit = "3.7.0"
Werkzeug = "3.0.2"
tblib = "^3.0.0"
pyupgrade = "^3.15.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
