# Generated by Django 2.2.9 on 2020-01-17 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_homepage_alert_message"),
        ("home", "0004_redirect_to_external_url"),
    ]

    operations = []
