# Generated by Django 2.2.13 on 2020-11-02 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_job_employer_logo"),
        ("home", "0008_update_listing_summary_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="logo",
            field=models.ForeignKey(
                help_text="For search engines and schema.org markup",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.CustomImage",
            ),
        ),
    ]
