# Generated by Django 2.2.13 on 2020-11-10 21:01

import django.db.models.deletion
from django.db import migrations, models

import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks

import bc.utils.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_job_employer_logo"),
        ("longform", "0002_add_streamfield_highlight_blocks"),
    ]

    operations = [
        migrations.AddField(
            model_name="longformpage",
            name="hero_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.CustomImage",
            ),
        ),
    ]
