# Generated by Django 2.2.15 on 2020-12-03 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("longform", "0003_add_hero_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="longformpage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.CustomImage",
            ),
        ),
    ]
