# Generated by Django 2.2.17 on 2021-02-01 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("longform", "0004_blank_hero_image"),
        ("longform", "0003_add_heading_helptext"),
    ]

    operations = []
