# Generated by Django 2.2.17 on 2021-02-01 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("longform", "0004_numbered_blocks"),
        ("longform", "0005_merge_helptext_and_image"),
    ]

    operations = []
