# Generated by Django 2.2.24 on 2021-10-18 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("longform", "0010_area_links_compulsory"),
        ("longform", "0010_add_and_relabel_heading_blocks"),
    ]

    operations = []
