# Generated by Django 2.2.24 on 2021-11-30 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("longform", "0011_add_accordion_blocks"),
        ("longform", "0013_add_area_links_block_fields"),
    ]

    operations = []
