# Generated by Django 3.2.9 on 2022-01-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("longform", "0017_typedtableblock_data_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="longformpage",
            name="intro_text",
            field=models.TextField(blank=True),
        ),
    ]
