# Generated by Django 3.2.9 on 2022-05-12 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("longform", "0018_longformpage_intro_text"),
        ("longform", "0021_auto_20220504_1323"),
    ]

    operations = []
