# Generated by Django 4.2.11 on 2024-06-27 18:39

import bc.longform.blocks
import bc.utils.blocks
from django.db import migrations
import wagtail.blocks
import wagtail.contrib.typed_table_block.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("longform", "0028_tableblock_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="longformchapterpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.blocks.CharBlock(
                            form_classname="full title",
                            group="Heading",
                            help_text='The link to this heading uses the heading text in lowercase, with no symbols, and with the spaces replaced with hyphens. e.g. "Lorem @ 2 ipsum" becomes "lorem-2-ipsum"',
                            icon="title",
                            label="Main heading",
                            template="patterns/molecules/streamfield/blocks/heading_block.html",
                        ),
                    ),
                    (
                        "subheading",
                        wagtail.blocks.CharBlock(
                            form_classname="full title",
                            group="Heading",
                            help_text='The link to this subheading uses the subheading text in lowercase, with no symbols, and with the spaces replaced with hyphens. e.g. "Lorem @ 2 ipsum" becomes "lorem-2-ipsum"',
                            icon="title",
                            template="patterns/molecules/streamfield/blocks/subheading_block.html",
                        ),
                    ),
                    (
                        "paragraph",
                        wagtail.blocks.RichTextBlock(
                            features=[
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "document-link",
                            ]
                        ),
                    ),
                    (
                        "image",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "alt_text",
                                    wagtail.blocks.CharBlock(
                                        help_text="Describe the information, not the picture. Leave blank if the image is purely decorative. Do not repeat captions or content already on the page.",
                                        required=False,
                                    ),
                                ),
                                ("caption", wagtail.blocks.CharBlock(required=False)),
                            ]
                        ),
                    ),
                    ("embed", wagtail.embeds.blocks.EmbedBlock()),
                    (
                        "local_area_links",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.RichTextBlock(
                                        default="<p><b>Find local information</b></p>",
                                        features=[
                                            "bold",
                                            "italic",
                                            "ol",
                                            "ul",
                                            "link",
                                            "document-link",
                                        ],
                                    ),
                                ),
                                (
                                    "introduction",
                                    wagtail.blocks.RichTextBlock(
                                        default="<p>While we finish building this new website, we’re keeping some local information on our old council websites</p>",
                                        features=[
                                            "bold",
                                            "italic",
                                            "ol",
                                            "ul",
                                            "link",
                                            "document-link",
                                        ],
                                    ),
                                ),
                                (
                                    "postcode_lookup_text",
                                    wagtail.blocks.RichTextBlock(
                                        default="<p>Enter your postcode to help us redirect you to the right place.</p>",
                                        features=[
                                            "bold",
                                            "italic",
                                            "ol",
                                            "ul",
                                            "link",
                                            "document-link",
                                        ],
                                        help_text="The text that appears on top of the postcode lookup input",
                                    ),
                                ),
                                (
                                    "area_lookup_text",
                                    wagtail.blocks.RichTextBlock(
                                        default="<p>Select your local area to help us direct you to the right place:</p>",
                                        features=[
                                            "bold",
                                            "italic",
                                            "ol",
                                            "ul",
                                            "link",
                                            "document-link",
                                        ],
                                        help_text="The text that appears on top of the list of local area links",
                                    ),
                                ),
                                (
                                    "aylesbury_vale_url",
                                    wagtail.blocks.URLBlock(label="Aylesbury Vale URL"),
                                ),
                                (
                                    "chiltern_url",
                                    wagtail.blocks.URLBlock(label="Chiltern URL"),
                                ),
                                (
                                    "south_bucks_url",
                                    wagtail.blocks.URLBlock(label="South Bucks URL"),
                                ),
                                (
                                    "wycombe_url",
                                    wagtail.blocks.URLBlock(label="Wycombe URL"),
                                ),
                            ]
                        ),
                    ),
                    (
                        "plain_text_table",
                        bc.utils.blocks.TableBlock(
                            group="Table",
                            help_text='This table will be displayed as plain text on the page.\n    You can add links to individuals cells by using the following\n    syntax: <em>[link text](www.gov.uk)</em>. This will output as\n    <a href="http://www.gov.uk">link text</a></li>',
                        ),
                    ),
                    (
                        "table",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "table",
                                    wagtail.contrib.typed_table_block.blocks.TypedTableBlock(
                                        [
                                            (
                                                "left_aligned_column",
                                                wagtail.blocks.StreamBlock(
                                                    [
                                                        (
                                                            "numeric",
                                                            wagtail.blocks.DecimalBlock(),
                                                        ),
                                                        (
                                                            "rich_text",
                                                            wagtail.blocks.RichTextBlock(),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "right_aligned_column",
                                                wagtail.blocks.StreamBlock(
                                                    [
                                                        (
                                                            "numeric",
                                                            wagtail.blocks.DecimalBlock(),
                                                        ),
                                                        (
                                                            "rich_text",
                                                            wagtail.blocks.RichTextBlock(),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                ("caption", wagtail.blocks.TextBlock(required=False)),
                            ],
                            group="Table",
                        ),
                    ),
                    (
                        "button",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(form_classname="title"),
                                ),
                                ("link_url", wagtail.blocks.URLBlock(required=False)),
                                (
                                    "link_page",
                                    wagtail.blocks.PageChooserBlock(required=False),
                                ),
                            ]
                        ),
                    ),
                    ("highlight", bc.utils.blocks.HighlightBlock()),
                    ("inset_text", bc.utils.blocks.InsetTextBlock()),
                    (
                        "fis_directory_widget",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Title of the widget", required=True
                                    ),
                                ),
                                (
                                    "search_placeholder",
                                    wagtail.blocks.CharBlock(
                                        help_text="Placeholder text for the search input",
                                        required=False,
                                    ),
                                ),
                                (
                                    "directory",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("send", "send"),
                                            ("familyinfo", "familyinfo"),
                                        ],
                                        help_text="Which directory to search",
                                    ),
                                ),
                                (
                                    "extra_query_params",
                                    wagtail.blocks.CharBlock(
                                        help_text="Extra query parameters to add to the search",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "subsubheading",
                        wagtail.blocks.CharBlock(
                            form_classname="full title",
                            group="Heading",
                            help_text='The link to this subsubheading uses the subsubheading text in lowercase, with no symbols, and with the spaces replaced with hyphens. e.g. "Lorem @ 2 ipsum" becomes "lorem-2-ipsum"',
                            icon="title",
                            label="H4",
                            template="patterns/molecules/streamfield/blocks/subsubheading_block.html",
                        ),
                    ),
                    (
                        "numbered_heading",
                        bc.longform.blocks.NumberedHeadingBlock(
                            help_text='Adds a number to the heading if is_numbered is not enabled on the long-form content page (e.g. 1. My heading). The link to this heading will be "section-x" where x is the heading number.'
                        ),
                    ),
                    (
                        "numbered_subheading",
                        bc.longform.blocks.NumberedSubheadingBlock(
                            help_text='Adds a number to the subheading (e.g. 1.1. My subheading). The link to this subheading will be "section-x.y" where x is the heading or chapter number, and y is the subheading number.'
                        ),
                    ),
                    (
                        "numbered_paragraph",
                        bc.longform.blocks.NumberedParagraphBlock(
                            help_text='Adds a number before the paragraph (e.g. 1.1.1.). The link to this paragraph will be "section-x.y.z" where x  is the heading or chapter number, y is the subheading number, and z is the paragraph number.'
                        ),
                    ),
                    (
                        "accordion",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "items",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        form_classname="full title",
                                                        icon="title",
                                                        label="Accordion title",
                                                    ),
                                                ),
                                                (
                                                    "content",
                                                    wagtail.blocks.StreamBlock(
                                                        [
                                                            (
                                                                "heading",
                                                                wagtail.blocks.CharBlock(
                                                                    form_classname="full title",
                                                                    group="Heading",
                                                                    help_text='The link to this heading uses the heading text in lowercase, with no symbols, and with the spaces replaced with hyphens. e.g. "Lorem @ 2 ipsum" becomes "lorem-2-ipsum"',
                                                                    icon="title",
                                                                    label="Main heading",
                                                                    template="patterns/molecules/streamfield/blocks/heading_block.html",
                                                                ),
                                                            ),
                                                            (
                                                                "subheading",
                                                                wagtail.blocks.CharBlock(
                                                                    form_classname="full title",
                                                                    group="Heading",
                                                                    help_text='The link to this subheading uses the subheading text in lowercase, with no symbols, and with the spaces replaced with hyphens. e.g. "Lorem @ 2 ipsum" becomes "lorem-2-ipsum"',
                                                                    icon="title",
                                                                    template="patterns/molecules/streamfield/blocks/subheading_block.html",
                                                                ),
                                                            ),
                                                            (
                                                                "paragraph",
                                                                wagtail.blocks.RichTextBlock(
                                                                    features=[
                                                                        "bold",
                                                                        "italic",
                                                                        "ol",
                                                                        "ul",
                                                                        "link",
                                                                        "document-link",
                                                                    ]
                                                                ),
                                                            ),
                                                            (
                                                                "image",
                                                                wagtail.blocks.StructBlock(
                                                                    [
                                                                        (
                                                                            "image",
                                                                            wagtail.images.blocks.ImageChooserBlock(),
                                                                        ),
                                                                        (
                                                                            "alt_text",
                                                                            wagtail.blocks.CharBlock(
                                                                                help_text="Describe the information, not the picture. Leave blank if the image is purely decorative. Do not repeat captions or content already on the page.",
                                                                                required=False,
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "caption",
                                                                            wagtail.blocks.CharBlock(
                                                                                required=False
                                                                            ),
                                                                        ),
                                                                    ]
                                                                ),
                                                            ),
                                                            (
                                                                "embed",
                                                                wagtail.embeds.blocks.EmbedBlock(),
                                                            ),
                                                            (
                                                                "local_area_links",
                                                                wagtail.blocks.StructBlock(
                                                                    [
                                                                        (
                                                                            "heading",
                                                                            wagtail.blocks.RichTextBlock(
                                                                                default="<p><b>Find local information</b></p>",
                                                                                features=[
                                                                                    "bold",
                                                                                    "italic",
                                                                                    "ol",
                                                                                    "ul",
                                                                                    "link",
                                                                                    "document-link",
                                                                                ],
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "introduction",
                                                                            wagtail.blocks.RichTextBlock(
                                                                                default="<p>While we finish building this new website, we’re keeping some local information on our old council websites</p>",
                                                                                features=[
                                                                                    "bold",
                                                                                    "italic",
                                                                                    "ol",
                                                                                    "ul",
                                                                                    "link",
                                                                                    "document-link",
                                                                                ],
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "postcode_lookup_text",
                                                                            wagtail.blocks.RichTextBlock(
                                                                                default="<p>Enter your postcode to help us redirect you to the right place.</p>",
                                                                                features=[
                                                                                    "bold",
                                                                                    "italic",
                                                                                    "ol",
                                                                                    "ul",
                                                                                    "link",
                                                                                    "document-link",
                                                                                ],
                                                                                help_text="The text that appears on top of the postcode lookup input",
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "area_lookup_text",
                                                                            wagtail.blocks.RichTextBlock(
                                                                                default="<p>Select your local area to help us direct you to the right place:</p>",
                                                                                features=[
                                                                                    "bold",
                                                                                    "italic",
                                                                                    "ol",
                                                                                    "ul",
                                                                                    "link",
                                                                                    "document-link",
                                                                                ],
                                                                                help_text="The text that appears on top of the list of local area links",
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "aylesbury_vale_url",
                                                                            wagtail.blocks.URLBlock(
                                                                                label="Aylesbury Vale URL"
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "chiltern_url",
                                                                            wagtail.blocks.URLBlock(
                                                                                label="Chiltern URL"
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "south_bucks_url",
                                                                            wagtail.blocks.URLBlock(
                                                                                label="South Bucks URL"
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "wycombe_url",
                                                                            wagtail.blocks.URLBlock(
                                                                                label="Wycombe URL"
                                                                            ),
                                                                        ),
                                                                    ]
                                                                ),
                                                            ),
                                                            (
                                                                "plain_text_table",
                                                                bc.utils.blocks.TableBlock(
                                                                    group="Table",
                                                                    help_text='This table will be displayed as plain text on the page.\n    You can add links to individuals cells by using the following\n    syntax: <em>[link text](www.gov.uk)</em>. This will output as\n    <a href="http://www.gov.uk">link text</a></li>',
                                                                ),
                                                            ),
                                                            (
                                                                "table",
                                                                wagtail.blocks.StructBlock(
                                                                    [
                                                                        (
                                                                            "table",
                                                                            wagtail.contrib.typed_table_block.blocks.TypedTableBlock(
                                                                                [
                                                                                    (
                                                                                        "left_aligned_column",
                                                                                        wagtail.blocks.StreamBlock(
                                                                                            [
                                                                                                (
                                                                                                    "numeric",
                                                                                                    wagtail.blocks.DecimalBlock(),
                                                                                                ),
                                                                                                (
                                                                                                    "rich_text",
                                                                                                    wagtail.blocks.RichTextBlock(),
                                                                                                ),
                                                                                            ]
                                                                                        ),
                                                                                    ),
                                                                                    (
                                                                                        "right_aligned_column",
                                                                                        wagtail.blocks.StreamBlock(
                                                                                            [
                                                                                                (
                                                                                                    "numeric",
                                                                                                    wagtail.blocks.DecimalBlock(),
                                                                                                ),
                                                                                                (
                                                                                                    "rich_text",
                                                                                                    wagtail.blocks.RichTextBlock(),
                                                                                                ),
                                                                                            ]
                                                                                        ),
                                                                                    ),
                                                                                ]
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "caption",
                                                                            wagtail.blocks.TextBlock(
                                                                                required=False
                                                                            ),
                                                                        ),
                                                                    ],
                                                                    group="Table",
                                                                ),
                                                            ),
                                                            (
                                                                "button",
                                                                wagtail.blocks.StructBlock(
                                                                    [
                                                                        (
                                                                            "text",
                                                                            wagtail.blocks.CharBlock(
                                                                                form_classname="title"
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "link_url",
                                                                            wagtail.blocks.URLBlock(
                                                                                required=False
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "link_page",
                                                                            wagtail.blocks.PageChooserBlock(
                                                                                required=False
                                                                            ),
                                                                        ),
                                                                    ]
                                                                ),
                                                            ),
                                                            (
                                                                "highlight",
                                                                bc.utils.blocks.HighlightBlock(),
                                                            ),
                                                            (
                                                                "inset_text",
                                                                bc.utils.blocks.InsetTextBlock(),
                                                            ),
                                                            (
                                                                "fis_directory_widget",
                                                                wagtail.blocks.StructBlock(
                                                                    [
                                                                        (
                                                                            "title",
                                                                            wagtail.blocks.CharBlock(
                                                                                help_text="Title of the widget",
                                                                                required=True,
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "search_placeholder",
                                                                            wagtail.blocks.CharBlock(
                                                                                help_text="Placeholder text for the search input",
                                                                                required=False,
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "directory",
                                                                            wagtail.blocks.ChoiceBlock(
                                                                                choices=[
                                                                                    (
                                                                                        "send",
                                                                                        "send",
                                                                                    ),
                                                                                    (
                                                                                        "familyinfo",
                                                                                        "familyinfo",
                                                                                    ),
                                                                                ],
                                                                                help_text="Which directory to search",
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "extra_query_params",
                                                                            wagtail.blocks.CharBlock(
                                                                                help_text="Extra query parameters to add to the search",
                                                                                required=False,
                                                                            ),
                                                                        ),
                                                                    ]
                                                                ),
                                                            ),
                                                        ],
                                                        label="Accordion content",
                                                    ),
                                                ),
                                            ]
                                        ),
                                        label="Accordion items",
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "detail",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        form_classname="full title",
                                        icon="title",
                                        label="Detail title",
                                    ),
                                ),
                                (
                                    "content",
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            "bold",
                                            "italic",
                                            "ol",
                                            "ul",
                                            "link",
                                            "document-link",
                                        ],
                                        label="Detail content",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    ("bar_chart", bc.utils.blocks.BarChartBlock()),
                    ("line_graph", bc.utils.blocks.LineChartBlock()),
                    ("pie_chart", bc.utils.blocks.PieChartBlock()),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="longformpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.blocks.CharBlock(
                            form_classname="full title",
                            group="Heading",
                            help_text='The link to this heading uses the heading text in lowercase, with no symbols, and with the spaces replaced with hyphens. e.g. "Lorem @ 2 ipsum" becomes "lorem-2-ipsum"',
                            icon="title",
                            label="Main heading",
                            template="patterns/molecules/streamfield/blocks/heading_block.html",
                        ),
                    ),
                    (
                        "subheading",
                        wagtail.blocks.CharBlock(
                            form_classname="full title",
                            group="Heading",
                            help_text='The link to this subheading uses the subheading text in lowercase, with no symbols, and with the spaces replaced with hyphens. e.g. "Lorem @ 2 ipsum" becomes "lorem-2-ipsum"',
                            icon="title",
                            template="patterns/molecules/streamfield/blocks/subheading_block.html",
                        ),
                    ),
                    (
                        "paragraph",
                        wagtail.blocks.RichTextBlock(
                            features=[
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "document-link",
                            ]
                        ),
                    ),
                    (
                        "image",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "alt_text",
                                    wagtail.blocks.CharBlock(
                                        help_text="Describe the information, not the picture. Leave blank if the image is purely decorative. Do not repeat captions or content already on the page.",
                                        required=False,
                                    ),
                                ),
                                ("caption", wagtail.blocks.CharBlock(required=False)),
                            ]
                        ),
                    ),
                    ("embed", wagtail.embeds.blocks.EmbedBlock()),
                    (
                        "local_area_links",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.RichTextBlock(
                                        default="<p><b>Find local information</b></p>",
                                        features=[
                                            "bold",
                                            "italic",
                                            "ol",
                                            "ul",
                                            "link",
                                            "document-link",
                                        ],
                                    ),
                                ),
                                (
                                    "introduction",
                                    wagtail.blocks.RichTextBlock(
                                        default="<p>While we finish building this new website, we’re keeping some local information on our old council websites</p>",
                                        features=[
                                            "bold",
                                            "italic",
                                            "ol",
                                            "ul",
                                            "link",
                                            "document-link",
                                        ],
                                    ),
                                ),
                                (
                                    "postcode_lookup_text",
                                    wagtail.blocks.RichTextBlock(
                                        default="<p>Enter your postcode to help us redirect you to the right place.</p>",
                                        features=[
                                            "bold",
                                            "italic",
                                            "ol",
                                            "ul",
                                            "link",
                                            "document-link",
                                        ],
                                        help_text="The text that appears on top of the postcode lookup input",
                                    ),
                                ),
                                (
                                    "area_lookup_text",
                                    wagtail.blocks.RichTextBlock(
                                        default="<p>Select your local area to help us direct you to the right place:</p>",
                                        features=[
                                            "bold",
                                            "italic",
                                            "ol",
                                            "ul",
                                            "link",
                                            "document-link",
                                        ],
                                        help_text="The text that appears on top of the list of local area links",
                                    ),
                                ),
                                (
                                    "aylesbury_vale_url",
                                    wagtail.blocks.URLBlock(label="Aylesbury Vale URL"),
                                ),
                                (
                                    "chiltern_url",
                                    wagtail.blocks.URLBlock(label="Chiltern URL"),
                                ),
                                (
                                    "south_bucks_url",
                                    wagtail.blocks.URLBlock(label="South Bucks URL"),
                                ),
                                (
                                    "wycombe_url",
                                    wagtail.blocks.URLBlock(label="Wycombe URL"),
                                ),
                            ]
                        ),
                    ),
                    (
                        "plain_text_table",
                        bc.utils.blocks.TableBlock(
                            group="Table",
                            help_text='This table will be displayed as plain text on the page.\n    You can add links to individuals cells by using the following\n    syntax: <em>[link text](www.gov.uk)</em>. This will output as\n    <a href="http://www.gov.uk">link text</a></li>',
                        ),
                    ),
                    (
                        "table",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "table",
                                    wagtail.contrib.typed_table_block.blocks.TypedTableBlock(
                                        [
                                            (
                                                "left_aligned_column",
                                                wagtail.blocks.StreamBlock(
                                                    [
                                                        (
                                                            "numeric",
                                                            wagtail.blocks.DecimalBlock(),
                                                        ),
                                                        (
                                                            "rich_text",
                                                            wagtail.blocks.RichTextBlock(),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "right_aligned_column",
                                                wagtail.blocks.StreamBlock(
                                                    [
                                                        (
                                                            "numeric",
                                                            wagtail.blocks.DecimalBlock(),
                                                        ),
                                                        (
                                                            "rich_text",
                                                            wagtail.blocks.RichTextBlock(),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                ("caption", wagtail.blocks.TextBlock(required=False)),
                            ],
                            group="Table",
                        ),
                    ),
                    (
                        "button",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(form_classname="title"),
                                ),
                                ("link_url", wagtail.blocks.URLBlock(required=False)),
                                (
                                    "link_page",
                                    wagtail.blocks.PageChooserBlock(required=False),
                                ),
                            ]
                        ),
                    ),
                    ("highlight", bc.utils.blocks.HighlightBlock()),
                    ("inset_text", bc.utils.blocks.InsetTextBlock()),
                    (
                        "fis_directory_widget",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Title of the widget", required=True
                                    ),
                                ),
                                (
                                    "search_placeholder",
                                    wagtail.blocks.CharBlock(
                                        help_text="Placeholder text for the search input",
                                        required=False,
                                    ),
                                ),
                                (
                                    "directory",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("send", "send"),
                                            ("familyinfo", "familyinfo"),
                                        ],
                                        help_text="Which directory to search",
                                    ),
                                ),
                                (
                                    "extra_query_params",
                                    wagtail.blocks.CharBlock(
                                        help_text="Extra query parameters to add to the search",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "subsubheading",
                        wagtail.blocks.CharBlock(
                            form_classname="full title",
                            group="Heading",
                            help_text='The link to this subsubheading uses the subsubheading text in lowercase, with no symbols, and with the spaces replaced with hyphens. e.g. "Lorem @ 2 ipsum" becomes "lorem-2-ipsum"',
                            icon="title",
                            label="H4",
                            template="patterns/molecules/streamfield/blocks/subsubheading_block.html",
                        ),
                    ),
                    (
                        "numbered_heading",
                        bc.longform.blocks.NumberedHeadingBlock(
                            help_text='Adds a number to the heading if is_numbered is not enabled on the long-form content page (e.g. 1. My heading). The link to this heading will be "section-x" where x is the heading number.'
                        ),
                    ),
                    (
                        "numbered_subheading",
                        bc.longform.blocks.NumberedSubheadingBlock(
                            help_text='Adds a number to the subheading (e.g. 1.1. My subheading). The link to this subheading will be "section-x.y" where x is the heading or chapter number, and y is the subheading number.'
                        ),
                    ),
                    (
                        "numbered_paragraph",
                        bc.longform.blocks.NumberedParagraphBlock(
                            help_text='Adds a number before the paragraph (e.g. 1.1.1.). The link to this paragraph will be "section-x.y.z" where x  is the heading or chapter number, y is the subheading number, and z is the paragraph number.'
                        ),
                    ),
                    (
                        "accordion",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "items",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        form_classname="full title",
                                                        icon="title",
                                                        label="Accordion title",
                                                    ),
                                                ),
                                                (
                                                    "content",
                                                    wagtail.blocks.StreamBlock(
                                                        [
                                                            (
                                                                "heading",
                                                                wagtail.blocks.CharBlock(
                                                                    form_classname="full title",
                                                                    group="Heading",
                                                                    help_text='The link to this heading uses the heading text in lowercase, with no symbols, and with the spaces replaced with hyphens. e.g. "Lorem @ 2 ipsum" becomes "lorem-2-ipsum"',
                                                                    icon="title",
                                                                    label="Main heading",
                                                                    template="patterns/molecules/streamfield/blocks/heading_block.html",
                                                                ),
                                                            ),
                                                            (
                                                                "subheading",
                                                                wagtail.blocks.CharBlock(
                                                                    form_classname="full title",
                                                                    group="Heading",
                                                                    help_text='The link to this subheading uses the subheading text in lowercase, with no symbols, and with the spaces replaced with hyphens. e.g. "Lorem @ 2 ipsum" becomes "lorem-2-ipsum"',
                                                                    icon="title",
                                                                    template="patterns/molecules/streamfield/blocks/subheading_block.html",
                                                                ),
                                                            ),
                                                            (
                                                                "paragraph",
                                                                wagtail.blocks.RichTextBlock(
                                                                    features=[
                                                                        "bold",
                                                                        "italic",
                                                                        "ol",
                                                                        "ul",
                                                                        "link",
                                                                        "document-link",
                                                                    ]
                                                                ),
                                                            ),
                                                            (
                                                                "image",
                                                                wagtail.blocks.StructBlock(
                                                                    [
                                                                        (
                                                                            "image",
                                                                            wagtail.images.blocks.ImageChooserBlock(),
                                                                        ),
                                                                        (
                                                                            "alt_text",
                                                                            wagtail.blocks.CharBlock(
                                                                                help_text="Describe the information, not the picture. Leave blank if the image is purely decorative. Do not repeat captions or content already on the page.",
                                                                                required=False,
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "caption",
                                                                            wagtail.blocks.CharBlock(
                                                                                required=False
                                                                            ),
                                                                        ),
                                                                    ]
                                                                ),
                                                            ),
                                                            (
                                                                "embed",
                                                                wagtail.embeds.blocks.EmbedBlock(),
                                                            ),
                                                            (
                                                                "local_area_links",
                                                                wagtail.blocks.StructBlock(
                                                                    [
                                                                        (
                                                                            "heading",
                                                                            wagtail.blocks.RichTextBlock(
                                                                                default="<p><b>Find local information</b></p>",
                                                                                features=[
                                                                                    "bold",
                                                                                    "italic",
                                                                                    "ol",
                                                                                    "ul",
                                                                                    "link",
                                                                                    "document-link",
                                                                                ],
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "introduction",
                                                                            wagtail.blocks.RichTextBlock(
                                                                                default="<p>While we finish building this new website, we’re keeping some local information on our old council websites</p>",
                                                                                features=[
                                                                                    "bold",
                                                                                    "italic",
                                                                                    "ol",
                                                                                    "ul",
                                                                                    "link",
                                                                                    "document-link",
                                                                                ],
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "postcode_lookup_text",
                                                                            wagtail.blocks.RichTextBlock(
                                                                                default="<p>Enter your postcode to help us redirect you to the right place.</p>",
                                                                                features=[
                                                                                    "bold",
                                                                                    "italic",
                                                                                    "ol",
                                                                                    "ul",
                                                                                    "link",
                                                                                    "document-link",
                                                                                ],
                                                                                help_text="The text that appears on top of the postcode lookup input",
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "area_lookup_text",
                                                                            wagtail.blocks.RichTextBlock(
                                                                                default="<p>Select your local area to help us direct you to the right place:</p>",
                                                                                features=[
                                                                                    "bold",
                                                                                    "italic",
                                                                                    "ol",
                                                                                    "ul",
                                                                                    "link",
                                                                                    "document-link",
                                                                                ],
                                                                                help_text="The text that appears on top of the list of local area links",
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "aylesbury_vale_url",
                                                                            wagtail.blocks.URLBlock(
                                                                                label="Aylesbury Vale URL"
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "chiltern_url",
                                                                            wagtail.blocks.URLBlock(
                                                                                label="Chiltern URL"
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "south_bucks_url",
                                                                            wagtail.blocks.URLBlock(
                                                                                label="South Bucks URL"
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "wycombe_url",
                                                                            wagtail.blocks.URLBlock(
                                                                                label="Wycombe URL"
                                                                            ),
                                                                        ),
                                                                    ]
                                                                ),
                                                            ),
                                                            (
                                                                "plain_text_table",
                                                                bc.utils.blocks.TableBlock(
                                                                    group="Table",
                                                                    help_text='This table will be displayed as plain text on the page.\n    You can add links to individuals cells by using the following\n    syntax: <em>[link text](www.gov.uk)</em>. This will output as\n    <a href="http://www.gov.uk">link text</a></li>',
                                                                ),
                                                            ),
                                                            (
                                                                "table",
                                                                wagtail.blocks.StructBlock(
                                                                    [
                                                                        (
                                                                            "table",
                                                                            wagtail.contrib.typed_table_block.blocks.TypedTableBlock(
                                                                                [
                                                                                    (
                                                                                        "left_aligned_column",
                                                                                        wagtail.blocks.StreamBlock(
                                                                                            [
                                                                                                (
                                                                                                    "numeric",
                                                                                                    wagtail.blocks.DecimalBlock(),
                                                                                                ),
                                                                                                (
                                                                                                    "rich_text",
                                                                                                    wagtail.blocks.RichTextBlock(),
                                                                                                ),
                                                                                            ]
                                                                                        ),
                                                                                    ),
                                                                                    (
                                                                                        "right_aligned_column",
                                                                                        wagtail.blocks.StreamBlock(
                                                                                            [
                                                                                                (
                                                                                                    "numeric",
                                                                                                    wagtail.blocks.DecimalBlock(),
                                                                                                ),
                                                                                                (
                                                                                                    "rich_text",
                                                                                                    wagtail.blocks.RichTextBlock(),
                                                                                                ),
                                                                                            ]
                                                                                        ),
                                                                                    ),
                                                                                ]
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "caption",
                                                                            wagtail.blocks.TextBlock(
                                                                                required=False
                                                                            ),
                                                                        ),
                                                                    ],
                                                                    group="Table",
                                                                ),
                                                            ),
                                                            (
                                                                "button",
                                                                wagtail.blocks.StructBlock(
                                                                    [
                                                                        (
                                                                            "text",
                                                                            wagtail.blocks.CharBlock(
                                                                                form_classname="title"
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "link_url",
                                                                            wagtail.blocks.URLBlock(
                                                                                required=False
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "link_page",
                                                                            wagtail.blocks.PageChooserBlock(
                                                                                required=False
                                                                            ),
                                                                        ),
                                                                    ]
                                                                ),
                                                            ),
                                                            (
                                                                "highlight",
                                                                bc.utils.blocks.HighlightBlock(),
                                                            ),
                                                            (
                                                                "inset_text",
                                                                bc.utils.blocks.InsetTextBlock(),
                                                            ),
                                                            (
                                                                "fis_directory_widget",
                                                                wagtail.blocks.StructBlock(
                                                                    [
                                                                        (
                                                                            "title",
                                                                            wagtail.blocks.CharBlock(
                                                                                help_text="Title of the widget",
                                                                                required=True,
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "search_placeholder",
                                                                            wagtail.blocks.CharBlock(
                                                                                help_text="Placeholder text for the search input",
                                                                                required=False,
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "directory",
                                                                            wagtail.blocks.ChoiceBlock(
                                                                                choices=[
                                                                                    (
                                                                                        "send",
                                                                                        "send",
                                                                                    ),
                                                                                    (
                                                                                        "familyinfo",
                                                                                        "familyinfo",
                                                                                    ),
                                                                                ],
                                                                                help_text="Which directory to search",
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "extra_query_params",
                                                                            wagtail.blocks.CharBlock(
                                                                                help_text="Extra query parameters to add to the search",
                                                                                required=False,
                                                                            ),
                                                                        ),
                                                                    ]
                                                                ),
                                                            ),
                                                        ],
                                                        label="Accordion content",
                                                    ),
                                                ),
                                            ]
                                        ),
                                        label="Accordion items",
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "detail",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        form_classname="full title",
                                        icon="title",
                                        label="Detail title",
                                    ),
                                ),
                                (
                                    "content",
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            "bold",
                                            "italic",
                                            "ol",
                                            "ul",
                                            "link",
                                            "document-link",
                                        ],
                                        label="Detail content",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    ("bar_chart", bc.utils.blocks.BarChartBlock()),
                    ("line_graph", bc.utils.blocks.LineChartBlock()),
                    ("pie_chart", bc.utils.blocks.PieChartBlock()),
                ]
            ),
        ),
    ]
