# Generated by Django 4.2.18 on 2025-03-17 08:06

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("longform", "0032_alter_longformchapterpage_body_and_more_"),
    ]

    operations = [
        migrations.AlterField(
            model_name="longformchapterpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("subheading", 1),
                    ("subsubheading", 2),
                    ("paragraph", 3),
                    ("image", 7),
                    ("embed", 8),
                    ("local_area_links", 17),
                    ("plain_text_table", 18),
                    ("table", 24),
                    ("button", 28),
                    ("highlight", 29),
                    ("inset_text", 30),
                    ("ehc_co_search", 31),
                    ("directory_search", 36),
                    ("form", 37),
                    ("numbered_heading", 38),
                    ("numbered_subheading", 39),
                    ("numbered_paragraph", 40),
                    ("accordion", 45),
                    ("detail", 48),
                    ("bar_chart", 49),
                    ("line_graph", 50),
                    ("pie_chart", 51),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "group": "Heading",
                            "help_text": 'The link to this heading uses the heading text in lowercase, with no symbols, and with the spaces replaced with hyphens. e.g. "Lorem @ 2 ipsum" becomes "lorem-2-ipsum"',
                            "icon": "title",
                            "label": "Main heading",
                            "template": "patterns/molecules/streamfield/blocks/heading_block.html",
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "group": "Heading",
                            "help_text": 'The link to this subheading uses the subheading text in lowercase, with no symbols, and with the spaces replaced with hyphens. e.g. "Lorem @ 2 ipsum" becomes "lorem-2-ipsum"',
                            "icon": "title",
                            "template": "patterns/molecules/streamfield/blocks/subheading_block.html",
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "group": "Heading",
                            "help_text": 'The link to this subsubheading uses the subsubheading text in lowercase, with no symbols, and with the spaces replaced with hyphens. e.g. "Lorem @ 2 ipsum" becomes "lorem-2-ipsum"',
                            "icon": "title",
                            "template": "patterns/molecules/streamfield/blocks/subsubheading_block.html",
                        },
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "document-link",
                            ]
                        },
                    ),
                    4: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Describe the information, not the picture. Leave blank if the image is purely decorative. Do not repeat captions or content already on the page.",
                            "required": False,
                        },
                    ),
                    6: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 4), ("alt_text", 5), ("caption", 6)]],
                        {},
                    ),
                    8: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                    9: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "<p><b>Find local information</b></p>",
                            "features": [
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "document-link",
                            ],
                        },
                    ),
                    10: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "<p>While we finish building this new website, we’re keeping some local information on our old council websites</p>",
                            "features": [
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "document-link",
                            ],
                        },
                    ),
                    11: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "<p>Enter your postcode to help us redirect you to the right place.</p>",
                            "features": [
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "document-link",
                            ],
                            "help_text": "The text that appears on top of the postcode lookup input",
                        },
                    ),
                    12: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "<p>Select your local area to help us direct you to the right place:</p>",
                            "features": [
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "document-link",
                            ],
                            "help_text": "The text that appears on top of the list of local area links",
                        },
                    ),
                    13: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Aylesbury Vale URL"},
                    ),
                    14: ("wagtail.blocks.URLBlock", (), {"label": "Chiltern URL"}),
                    15: ("wagtail.blocks.URLBlock", (), {"label": "South Bucks URL"}),
                    16: ("wagtail.blocks.URLBlock", (), {"label": "Wycombe URL"}),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 9),
                                ("introduction", 10),
                                ("postcode_lookup_text", 11),
                                ("area_lookup_text", 12),
                                ("aylesbury_vale_url", 13),
                                ("chiltern_url", 14),
                                ("south_bucks_url", 15),
                                ("wycombe_url", 16),
                            ]
                        ],
                        {},
                    ),
                    18: (
                        "bc.utils.blocks.TableBlock",
                        (),
                        {
                            "group": "Table",
                            "help_text": 'This table will be displayed as plain text on the page.\n    You can add links to individuals cells by using the following\n    syntax: <em>[link text](www.gov.uk)</em>. This will output as\n    <a href="http://www.gov.uk">link text</a></li>',
                        },
                    ),
                    19: ("wagtail.blocks.DecimalBlock", (), {}),
                    20: ("wagtail.blocks.RichTextBlock", (), {}),
                    21: (
                        "wagtail.blocks.StreamBlock",
                        [[("numeric", 19), ("rich_text", 20)]],
                        {},
                    ),
                    22: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("left_aligned_column", 21), ("right_aligned_column", 21)]],
                        {},
                    ),
                    23: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("table", 22), ("caption", 23)]],
                        {"group": "Table"},
                    ),
                    25: ("wagtail.blocks.CharBlock", (), {"form_classname": "title"}),
                    26: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    27: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 25), ("link_url", 26), ("link_page", 27)]],
                        {},
                    ),
                    29: ("bc.utils.blocks.HighlightBlock", (), {}),
                    30: ("bc.utils.blocks.InsetTextBlock", (), {}),
                    31: (
                        "bc.utils.blocks.EHCCoSearchBlock",
                        (),
                        {"label": "EHCCo Search"},
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title of the widget", "required": True},
                    ),
                    33: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Placeholder text for the search input",
                            "required": False,
                        },
                    ),
                    34: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bucks_online_directory", "Bucks Online Directory"),
                                ("familyinfo", "Family Information Service"),
                                ("send", "SEND"),
                            ],
                            "help_text": "Which directory to search",
                        },
                    ),
                    35: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Extra query parameters to add to the search, e.g. ?collection=things-to-do&needs=autism",
                            "required": False,
                        },
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 32),
                                ("search_placeholder", 33),
                                ("directory", 34),
                                ("extra_query_params", 35),
                            ]
                        ],
                        {},
                    ),
                    37: ("bc.forms.blocks.EmbeddedFormBlock", (), {}),
                    38: (
                        "bc.longform.blocks.NumberedHeadingBlock",
                        (),
                        {
                            "help_text": 'Adds a number to the heading if is_numbered is not enabled on the long-form content page (e.g. 1. My heading). The link to this heading will be "section-x" where x is the heading number.'
                        },
                    ),
                    39: (
                        "bc.longform.blocks.NumberedSubheadingBlock",
                        (),
                        {
                            "help_text": 'Adds a number to the subheading (e.g. 1.1. My subheading). The link to this subheading will be "section-x.y" where x is the heading or chapter number, and y is the subheading number.'
                        },
                    ),
                    40: (
                        "bc.longform.blocks.NumberedParagraphBlock",
                        (),
                        {
                            "help_text": 'Adds a number before the paragraph (e.g. 1.1.1.). The link to this paragraph will be "section-x.y.z" where x  is the heading or chapter number, y is the subheading number, and z is the paragraph number.'
                        },
                    ),
                    41: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "icon": "title",
                            "label": "Accordion title",
                        },
                    ),
                    42: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("heading", 0),
                                ("subheading", 1),
                                ("subsubheading", 2),
                                ("paragraph", 3),
                                ("image", 7),
                                ("embed", 8),
                                ("local_area_links", 17),
                                ("plain_text_table", 18),
                                ("table", 24),
                                ("button", 28),
                                ("highlight", 29),
                                ("inset_text", 30),
                                ("ehc_co_search", 31),
                                ("directory_search", 36),
                                ("form", 37),
                            ]
                        ],
                        {"label": "Accordion content"},
                    ),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 41), ("content", 42)]],
                        {},
                    ),
                    44: (
                        "wagtail.blocks.ListBlock",
                        (43,),
                        {"label": "Accordion items"},
                    ),
                    45: ("wagtail.blocks.StructBlock", [[("items", 44)]], {}),
                    46: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "icon": "title",
                            "label": "Detail title",
                        },
                    ),
                    47: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "document-link",
                            ],
                            "label": "Detail content",
                        },
                    ),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 46), ("content", 47)]],
                        {},
                    ),
                    49: ("bc.utils.blocks.BarChartBlock", (), {}),
                    50: ("bc.utils.blocks.LineChartBlock", (), {}),
                    51: ("bc.utils.blocks.PieChartBlock", (), {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="longformpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("subheading", 1),
                    ("subsubheading", 2),
                    ("paragraph", 3),
                    ("image", 7),
                    ("embed", 8),
                    ("local_area_links", 17),
                    ("plain_text_table", 18),
                    ("table", 24),
                    ("button", 28),
                    ("highlight", 29),
                    ("inset_text", 30),
                    ("ehc_co_search", 31),
                    ("directory_search", 36),
                    ("form", 37),
                    ("numbered_heading", 38),
                    ("numbered_subheading", 39),
                    ("numbered_paragraph", 40),
                    ("accordion", 45),
                    ("detail", 48),
                    ("bar_chart", 49),
                    ("line_graph", 50),
                    ("pie_chart", 51),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "group": "Heading",
                            "help_text": 'The link to this heading uses the heading text in lowercase, with no symbols, and with the spaces replaced with hyphens. e.g. "Lorem @ 2 ipsum" becomes "lorem-2-ipsum"',
                            "icon": "title",
                            "label": "Main heading",
                            "template": "patterns/molecules/streamfield/blocks/heading_block.html",
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "group": "Heading",
                            "help_text": 'The link to this subheading uses the subheading text in lowercase, with no symbols, and with the spaces replaced with hyphens. e.g. "Lorem @ 2 ipsum" becomes "lorem-2-ipsum"',
                            "icon": "title",
                            "template": "patterns/molecules/streamfield/blocks/subheading_block.html",
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "group": "Heading",
                            "help_text": 'The link to this subsubheading uses the subsubheading text in lowercase, with no symbols, and with the spaces replaced with hyphens. e.g. "Lorem @ 2 ipsum" becomes "lorem-2-ipsum"',
                            "icon": "title",
                            "template": "patterns/molecules/streamfield/blocks/subsubheading_block.html",
                        },
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "document-link",
                            ]
                        },
                    ),
                    4: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Describe the information, not the picture. Leave blank if the image is purely decorative. Do not repeat captions or content already on the page.",
                            "required": False,
                        },
                    ),
                    6: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 4), ("alt_text", 5), ("caption", 6)]],
                        {},
                    ),
                    8: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                    9: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "<p><b>Find local information</b></p>",
                            "features": [
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "document-link",
                            ],
                        },
                    ),
                    10: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "<p>While we finish building this new website, we’re keeping some local information on our old council websites</p>",
                            "features": [
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "document-link",
                            ],
                        },
                    ),
                    11: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "<p>Enter your postcode to help us redirect you to the right place.</p>",
                            "features": [
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "document-link",
                            ],
                            "help_text": "The text that appears on top of the postcode lookup input",
                        },
                    ),
                    12: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "<p>Select your local area to help us direct you to the right place:</p>",
                            "features": [
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "document-link",
                            ],
                            "help_text": "The text that appears on top of the list of local area links",
                        },
                    ),
                    13: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Aylesbury Vale URL"},
                    ),
                    14: ("wagtail.blocks.URLBlock", (), {"label": "Chiltern URL"}),
                    15: ("wagtail.blocks.URLBlock", (), {"label": "South Bucks URL"}),
                    16: ("wagtail.blocks.URLBlock", (), {"label": "Wycombe URL"}),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 9),
                                ("introduction", 10),
                                ("postcode_lookup_text", 11),
                                ("area_lookup_text", 12),
                                ("aylesbury_vale_url", 13),
                                ("chiltern_url", 14),
                                ("south_bucks_url", 15),
                                ("wycombe_url", 16),
                            ]
                        ],
                        {},
                    ),
                    18: (
                        "bc.utils.blocks.TableBlock",
                        (),
                        {
                            "group": "Table",
                            "help_text": 'This table will be displayed as plain text on the page.\n    You can add links to individuals cells by using the following\n    syntax: <em>[link text](www.gov.uk)</em>. This will output as\n    <a href="http://www.gov.uk">link text</a></li>',
                        },
                    ),
                    19: ("wagtail.blocks.DecimalBlock", (), {}),
                    20: ("wagtail.blocks.RichTextBlock", (), {}),
                    21: (
                        "wagtail.blocks.StreamBlock",
                        [[("numeric", 19), ("rich_text", 20)]],
                        {},
                    ),
                    22: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("left_aligned_column", 21), ("right_aligned_column", 21)]],
                        {},
                    ),
                    23: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("table", 22), ("caption", 23)]],
                        {"group": "Table"},
                    ),
                    25: ("wagtail.blocks.CharBlock", (), {"form_classname": "title"}),
                    26: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    27: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 25), ("link_url", 26), ("link_page", 27)]],
                        {},
                    ),
                    29: ("bc.utils.blocks.HighlightBlock", (), {}),
                    30: ("bc.utils.blocks.InsetTextBlock", (), {}),
                    31: (
                        "bc.utils.blocks.EHCCoSearchBlock",
                        (),
                        {"label": "EHCCo Search"},
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title of the widget", "required": True},
                    ),
                    33: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Placeholder text for the search input",
                            "required": False,
                        },
                    ),
                    34: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bucks_online_directory", "Bucks Online Directory"),
                                ("familyinfo", "Family Information Service"),
                                ("send", "SEND"),
                            ],
                            "help_text": "Which directory to search",
                        },
                    ),
                    35: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Extra query parameters to add to the search, e.g. ?collection=things-to-do&needs=autism",
                            "required": False,
                        },
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 32),
                                ("search_placeholder", 33),
                                ("directory", 34),
                                ("extra_query_params", 35),
                            ]
                        ],
                        {},
                    ),
                    37: ("bc.forms.blocks.EmbeddedFormBlock", (), {}),
                    38: (
                        "bc.longform.blocks.NumberedHeadingBlock",
                        (),
                        {
                            "help_text": 'Adds a number to the heading if is_numbered is not enabled on the long-form content page (e.g. 1. My heading). The link to this heading will be "section-x" where x is the heading number.'
                        },
                    ),
                    39: (
                        "bc.longform.blocks.NumberedSubheadingBlock",
                        (),
                        {
                            "help_text": 'Adds a number to the subheading (e.g. 1.1. My subheading). The link to this subheading will be "section-x.y" where x is the heading or chapter number, and y is the subheading number.'
                        },
                    ),
                    40: (
                        "bc.longform.blocks.NumberedParagraphBlock",
                        (),
                        {
                            "help_text": 'Adds a number before the paragraph (e.g. 1.1.1.). The link to this paragraph will be "section-x.y.z" where x  is the heading or chapter number, y is the subheading number, and z is the paragraph number.'
                        },
                    ),
                    41: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "icon": "title",
                            "label": "Accordion title",
                        },
                    ),
                    42: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("heading", 0),
                                ("subheading", 1),
                                ("subsubheading", 2),
                                ("paragraph", 3),
                                ("image", 7),
                                ("embed", 8),
                                ("local_area_links", 17),
                                ("plain_text_table", 18),
                                ("table", 24),
                                ("button", 28),
                                ("highlight", 29),
                                ("inset_text", 30),
                                ("ehc_co_search", 31),
                                ("directory_search", 36),
                                ("form", 37),
                            ]
                        ],
                        {"label": "Accordion content"},
                    ),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 41), ("content", 42)]],
                        {},
                    ),
                    44: (
                        "wagtail.blocks.ListBlock",
                        (43,),
                        {"label": "Accordion items"},
                    ),
                    45: ("wagtail.blocks.StructBlock", [[("items", 44)]], {}),
                    46: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "icon": "title",
                            "label": "Detail title",
                        },
                    ),
                    47: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "document-link",
                            ],
                            "label": "Detail content",
                        },
                    ),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 46), ("content", 47)]],
                        {},
                    ),
                    49: ("bc.utils.blocks.BarChartBlock", (), {}),
                    50: ("bc.utils.blocks.LineChartBlock", (), {}),
                    51: ("bc.utils.blocks.PieChartBlock", (), {}),
                },
            ),
        ),
    ]
