# Generated by Django 2.2.7 on 2019-12-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("standardpages", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="informationpage",
            name="introduction",
        ),
    ]
