# Generated by Django 2.2.9 on 2020-01-17 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("standardpages", "0007_redirect_to_external_url"),
        ("standardpages", "0007_amend_local_area_links_postscript"),
    ]

    operations = []
