# Generated by Django 2.2.10 on 2020-03-31 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("standardpages", "0010_image_block"),
        ("standardpages", "0010_button_block"),
    ]

    operations = []
