# Generated by Django 2.2.10 on 2020-04-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standardpages", "0012_auto_20200331_1646"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexpage",
            name="show_live_chat_client",
            field=models.BooleanField(
                default=False, help_text="Show live chat support client on this page"
            ),
        ),
        migrations.AddField(
            model_name="informationpage",
            name="show_live_chat_client",
            field=models.BooleanField(
                default=False, help_text="Show live chat support client on this page"
            ),
        ),
    ]
