# Generated by Django 2.2.24 on 2021-11-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standardpages", "0022_heading_subheading_helptext"),
    ]

    operations = [
        migrations.AddField(
            model_name="informationpage",
            name="display_contents",
            field=models.BooleanField(default=False),
        ),
    ]
