# Generated by Django 3.2.9 on 2022-01-13 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("standardpages", "0025_informationpage_display_contents"),
        ("standardpages", "0027_use_old_table_block_when_nested"),
    ]

    operations = []
