# Generated by Django 3.2.9 on 2022-01-31 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("standardpages", "0028_add_inset_text_block"),
        ("standardpages", "0028_merge_20220113_0820"),
    ]

    operations = []
