# Generated by Django 3.2.9 on 2022-05-04 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("standardpages", "0028_aligned_columns_data_migration"),
        ("standardpages", "0029_merge_20220131_0726"),
    ]

    operations = []
