# Generated by Django 3.2.9 on 2022-05-12 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("standardpages", "0027_informationpage_intro_text"),
        ("standardpages", "0031_alter_informationpage_body"),
    ]

    operations = []
