# Generated by Django 2.2.13 on 2020-11-10 16:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "canonical_term",
                    models.CharField(
                        help_text="A word or phrase that returns intended search results",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "synonyms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        help_text="A list of other terms which should match pages containing the canonical term. Separate with commas, multiple word phrases are supported.",
                        size=None,
                    ),
                ),
            ],
            options={
                "verbose_name": "Search synonym",
            },
        ),
    ]
