# Generated by Django 2.2.24 on 2021-11-11 08:12

import django.db.models.deletion
from django.db import migrations, models

import modelcluster.fields
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks

import bc.area_finder.utils
import bc.utils.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0062_comment_models_and_pagesubscription"),
        ("images", "0003_job_employer_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                ("social_text", models.CharField(blank=True, max_length=255)),
                (
                    "listing_title",
                    models.CharField(
                        blank=True,
                        help_text="Override the page title used when this page appears in listings",
                        max_length=255,
                    ),
                ),
                (
                    "listing_summary",
                    models.CharField(
                        blank=True,
                        help_text="The text summary used when this page appears in listings. It's also used as the description for search engines if the 'Meta description' field above is not defined.",
                        max_length=255,
                    ),
                ),
                (
                    "redirect_to",
                    models.URLField(
                        blank=True,
                        help_text="Entering a URL here will prevent the page from being visited, and will instead redirect the user.",
                        verbose_name="Redirect to external URL",
                    ),
                ),
                (
                    "show_live_chat_client",
                    models.BooleanField(
                        default=False,
                        help_text="Show live chat support client on this page",
                    ),
                ),
                ("map_location", models.TextField(blank=True)),
                ("latlng", models.CharField(blank=True, max_length=250)),
                ("street_address_1", models.CharField(blank=True, max_length=255)),
                ("street_address_2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=255)),
                (
                    "postcode",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        validators=[bc.area_finder.utils.validate_postcode],
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True,
                        help_text="This will be used for a tel: anchor link in the page",
                        max_length=16,
                    ),
                ),
                ("email_address", models.EmailField(blank=True, max_length=254)),
                (
                    "body",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "heading",
                                wagtail.core.blocks.CharBlock(
                                    form_classname="full title",
                                    group="Heading",
                                    help_text='The link to this heading uses the heading text in lowercase, with no symbols, and with the spaces replaced with hyphens. e.g. "Lorem @ 2 ipsum" becomes "lorem-2-ipsum"',
                                    icon="title",
                                    label="Main heading",
                                    template="patterns/molecules/streamfield/blocks/heading_block.html",
                                ),
                            ),
                            (
                                "subheading",
                                wagtail.core.blocks.CharBlock(
                                    form_classname="full title",
                                    group="Heading",
                                    help_text='The link to this subheading uses the subheading text in lowercase, with no symbols, and with the spaces replaced with hyphens. e.g. "Lorem @ 2 ipsum" becomes "lorem-2-ipsum"',
                                    icon="title",
                                    template="patterns/molecules/streamfield/blocks/subheading_block.html",
                                ),
                            ),
                            (
                                "paragraph",
                                wagtail.core.blocks.RichTextBlock(
                                    features=[
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "link",
                                        "document-link",
                                    ]
                                ),
                            ),
                            (
                                "image",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(),
                                        ),
                                        (
                                            "alt_text",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="Describe the information, not the picture. Leave blank if the image is purely decorative. Do not repeat captions or content already on the page.",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "caption",
                                            wagtail.core.blocks.CharBlock(
                                                required=False
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            ("embed", wagtail.embeds.blocks.EmbedBlock()),
                            (
                                "local_area_links",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "introduction",
                                            wagtail.core.blocks.RichTextBlock(
                                                default="<p>Select your local area for information:</p>",
                                                features=[
                                                    "bold",
                                                    "italic",
                                                    "ol",
                                                    "ul",
                                                    "link",
                                                    "document-link",
                                                ],
                                            ),
                                        ),
                                        (
                                            "aylesbury_vale_url",
                                            wagtail.core.blocks.URLBlock(
                                                label="Aylesbury Vale URL",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "chiltern_url",
                                            wagtail.core.blocks.URLBlock(
                                                label="Chiltern URL", required=False
                                            ),
                                        ),
                                        (
                                            "south_bucks_url",
                                            wagtail.core.blocks.URLBlock(
                                                label="South Bucks URL", required=False
                                            ),
                                        ),
                                        (
                                            "wycombe_url",
                                            wagtail.core.blocks.URLBlock(
                                                label="Wycombe URL", required=False
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            ("table", wagtail.contrib.table_block.blocks.TableBlock()),
                            (
                                "button",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "text",
                                            wagtail.core.blocks.CharBlock(
                                                form_classname="title"
                                            ),
                                        ),
                                        (
                                            "link_url",
                                            wagtail.core.blocks.URLBlock(
                                                required=False
                                            ),
                                        ),
                                        (
                                            "link_page",
                                            wagtail.core.blocks.PageChooserBlock(
                                                required=False
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            ("highlight", bc.utils.blocks.HighlightBlock()),
                            (
                                "accordion",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "items",
                                            wagtail.core.blocks.ListBlock(
                                                wagtail.core.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.core.blocks.CharBlock(
                                                                form_classname="full title",
                                                                icon="title",
                                                                label="Accordion title",
                                                            ),
                                                        ),
                                                        (
                                                            "content",
                                                            wagtail.core.blocks.StreamBlock(
                                                                [
                                                                    (
                                                                        "heading",
                                                                        wagtail.core.blocks.CharBlock(
                                                                            form_classname="full title",
                                                                            group="Heading",
                                                                            help_text='The link to this heading uses the heading text in lowercase, with no symbols, and with the spaces replaced with hyphens. e.g. "Lorem @ 2 ipsum" becomes "lorem-2-ipsum"',
                                                                            icon="title",
                                                                            label="Main heading",
                                                                            template="patterns/molecules/streamfield/blocks/heading_block.html",
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "subheading",
                                                                        wagtail.core.blocks.CharBlock(
                                                                            form_classname="full title",
                                                                            group="Heading",
                                                                            help_text='The link to this subheading uses the subheading text in lowercase, with no symbols, and with the spaces replaced with hyphens. e.g. "Lorem @ 2 ipsum" becomes "lorem-2-ipsum"',
                                                                            icon="title",
                                                                            template="patterns/molecules/streamfield/blocks/subheading_block.html",
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "paragraph",
                                                                        wagtail.core.blocks.RichTextBlock(
                                                                            features=[
                                                                                "bold",
                                                                                "italic",
                                                                                "ol",
                                                                                "ul",
                                                                                "link",
                                                                                "document-link",
                                                                            ]
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "image",
                                                                        wagtail.core.blocks.StructBlock(
                                                                            [
                                                                                (
                                                                                    "image",
                                                                                    wagtail.images.blocks.ImageChooserBlock(),
                                                                                ),
                                                                                (
                                                                                    "alt_text",
                                                                                    wagtail.core.blocks.CharBlock(
                                                                                        help_text="Describe the information, not the picture. Leave blank if the image is purely decorative. Do not repeat captions or content already on the page.",
                                                                                        required=False,
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "caption",
                                                                                    wagtail.core.blocks.CharBlock(
                                                                                        required=False
                                                                                    ),
                                                                                ),
                                                                            ]
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "embed",
                                                                        wagtail.embeds.blocks.EmbedBlock(),
                                                                    ),
                                                                    (
                                                                        "local_area_links",
                                                                        wagtail.core.blocks.StructBlock(
                                                                            [
                                                                                (
                                                                                    "introduction",
                                                                                    wagtail.core.blocks.RichTextBlock(
                                                                                        default="<p>Select your local area for information:</p>",
                                                                                        features=[
                                                                                            "bold",
                                                                                            "italic",
                                                                                            "ol",
                                                                                            "ul",
                                                                                            "link",
                                                                                            "document-link",
                                                                                        ],
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "aylesbury_vale_url",
                                                                                    wagtail.core.blocks.URLBlock(
                                                                                        label="Aylesbury Vale URL",
                                                                                        required=False,
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "chiltern_url",
                                                                                    wagtail.core.blocks.URLBlock(
                                                                                        label="Chiltern URL",
                                                                                        required=False,
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "south_bucks_url",
                                                                                    wagtail.core.blocks.URLBlock(
                                                                                        label="South Bucks URL",
                                                                                        required=False,
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "wycombe_url",
                                                                                    wagtail.core.blocks.URLBlock(
                                                                                        label="Wycombe URL",
                                                                                        required=False,
                                                                                    ),
                                                                                ),
                                                                            ]
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "table",
                                                                        wagtail.contrib.table_block.blocks.TableBlock(),
                                                                    ),
                                                                    (
                                                                        "button",
                                                                        wagtail.core.blocks.StructBlock(
                                                                            [
                                                                                (
                                                                                    "text",
                                                                                    wagtail.core.blocks.CharBlock(
                                                                                        form_classname="title"
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "link_url",
                                                                                    wagtail.core.blocks.URLBlock(
                                                                                        required=False
                                                                                    ),
                                                                                ),
                                                                                (
                                                                                    "link_page",
                                                                                    wagtail.core.blocks.PageChooserBlock(
                                                                                        required=False
                                                                                    ),
                                                                                ),
                                                                            ]
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "highlight",
                                                                        bc.utils.blocks.HighlightBlock(),
                                                                    ),
                                                                ],
                                                                label="Accordion content",
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                                label="Accordion items",
                                            ),
                                        )
                                    ]
                                ),
                            ),
                            (
                                "detail",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.core.blocks.CharBlock(
                                                form_classname="full title",
                                                icon="title",
                                                label="Detail title",
                                            ),
                                        ),
                                        (
                                            "content",
                                            wagtail.core.blocks.RichTextBlock(
                                                features=[
                                                    "bold",
                                                    "italic",
                                                    "ol",
                                                    "ul",
                                                    "link",
                                                    "document-link",
                                                ],
                                                label="Detail content",
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ]
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.CustomImage",
                    ),
                ),
                (
                    "listing_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Choose the image you wish to be displayed when this page appears in listings",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.CustomImage",
                    ),
                ),
                (
                    "social_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.CustomImage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="LocationPageRelatedPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "source_page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_pages",
                        to="location.LocationPage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LocationIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                ("social_text", models.CharField(blank=True, max_length=255)),
                (
                    "listing_title",
                    models.CharField(
                        blank=True,
                        help_text="Override the page title used when this page appears in listings",
                        max_length=255,
                    ),
                ),
                (
                    "listing_summary",
                    models.CharField(
                        blank=True,
                        help_text="The text summary used when this page appears in listings. It's also used as the description for search engines if the 'Meta description' field above is not defined.",
                        max_length=255,
                    ),
                ),
                (
                    "redirect_to",
                    models.URLField(
                        blank=True,
                        help_text="Entering a URL here will prevent the page from being visited, and will instead redirect the user.",
                        verbose_name="Redirect to external URL",
                    ),
                ),
                (
                    "show_live_chat_client",
                    models.BooleanField(
                        default=False,
                        help_text="Show live chat support client on this page",
                    ),
                ),
                ("body", wagtail.core.fields.RichTextField()),
                (
                    "listing_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Choose the image you wish to be displayed when this page appears in listings",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.CustomImage",
                    ),
                ),
                (
                    "social_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.CustomImage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
