# Generated by Django 2.2.24 on 2021-11-22 07:27

from django.db import migrations

import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationpage",
            name="map_info_text",
            field=wagtail.core.fields.RichTextField(
                help_text="Content to display in popup window above the map", null=True
            ),
        ),
    ]
