# Generated by Django 2.2.9 on 2020-01-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="talentlinkjob",
            name="expected_start_date",
            field=models.DateField(null=True),
        ),
    ]
