# Generated by Django 2.2.9 on 2020-01-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TalentLinkJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("talentlink_id", models.IntegerField(unique=True)),
                ("job_number", models.CharField(max_length=10, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=255)),
                ("salary_range", models.CharField(max_length=255)),
                ("working_hours", models.CharField(max_length=255)),
                ("closing_date", models.DateField()),
                ("expected_start_date", models.DateField(null=True)),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "searchable_salary",
                    models.CharField(
                        help_text="Salary group for filtering", max_length=255
                    ),
                ),
                ("searchable_location", models.CharField(max_length=255)),
                ("is_published", models.BooleanField(default=True)),
                ("posting_start_date", models.DateTimeField()),
                ("posting_end_date", models.DateTimeField()),
                ("show_apply_button", models.BooleanField(default=True)),
            ],
        ),
    ]
