# Generated by Django 2.2.9 on 2020-01-28 19:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0002_talentlinkjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="talentlinkjob",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="talentlinkjob",
            name="last_imported",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="talentlinkjob",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
