# Generated by Django 2.2.9 on 2020-01-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0002_recruitmenthomepage"),
        ("recruitment", "0002_add_job_expected_start_date"),
    ]

    operations = []
