# Generated by Django 2.2.9 on 2020-01-22 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0003_merge_20200116_1133"),
        ("recruitment", "0002_recruitmenthomepage_redirect_to"),
    ]

    operations = []
