# Generated by Django 2.2.9 on 2020-02-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0003_add_job_timestamp_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="talentlinkjob",
            name="job_number",
            field=models.CharField(max_length=10),
        ),
    ]
