# Generated by Django 2.2.9 on 2020-01-31 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0003_add_job_timestamp_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Job categories",
            },
        ),
        migrations.AlterField(
            model_name="talentlinkjob",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="recruitment.JobCategory",
            ),
        ),
    ]
