# Generated by Django 2.2.9 on 2020-02-03 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0004_job_categories"),
        ("recruitment", "0004_non_unique_job_numbers"),
    ]

    operations = []
