# Generated by Django 2.2.9 on 2020-02-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0005_merge_20200203_1503"),
    ]

    operations = [
        migrations.AddField(
            model_name="talentlinkjob",
            name="short_description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
