# Generated by Django 2.2.10 on 2020-02-07 13:35

import django.db.models.deletion
from django.db import migrations, models

import modelcluster.fields

from bc.recruitment.models import JobCategory


"""
Insert slugs for existing Job Category that doesn't have one set
"""


def update_jobcategory_slug(apps, schema_editor):
    for category in JobCategory.objects.all():
        if not category.slug:
            # The slug will be autogenerated on save() if empty
            category.save()


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0008_jobcategory_slug"),
    ]

    operations = [
        migrations.RunPython(
            update_jobcategory_slug, reverse_code=migrations.RunPython.noop
        )
    ]
