# Generated by Django 2.2.9 on 2020-02-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0009_insert_jobcategory_slugs"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruitmenthomepage",
            name="hero_link_text",
            field=models.CharField(
                default="", help_text="e.g. Browse jobs", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recruitmenthomepage",
            name="hero_title",
            field=models.CharField(
                help_text="e.g. Finding a job in Buckinghamshire", max_length=255
            ),
        ),
    ]
