# Generated by Django 2.2.10 on 2020-02-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0012_job_subcategories"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobcategory",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
