# Generated by Django 2.2.9 on 2020-02-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0012_job_subcategories"),
    ]

    operations = [
        migrations.AddField(
            model_name="talentlinkjob",
            name="application_url_query",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
