# Generated by Django 2.2.10 on 2020-02-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0012_job_subcategories"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobAlertSubscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("search", models.TextField(default="{}", editable=False)),
                ("confirmed", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "token",
                    models.CharField(editable=False, max_length=255, unique=True),
                ),
            ],
        ),
    ]
