# Generated by Django 2.2.9 on 2020-02-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0013_job_alert_subscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobAlertNotificationTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started", models.DateTimeField()),
                ("ended", models.DateTimeField(null=True)),
                ("is_successful", models.BooleanField(default=False)),
            ],
        ),
    ]
