# Generated by Django 2.2.9 on 2020-02-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0014_add_job_alert_notification_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobalertnotificationtask",
            name="started",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
