# Generated by Django 2.2.10 on 2020-03-11 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0013_add_job_application_url_query"),
        ("recruitment", "0015_job_alert_task_started_auto_timestamp"),
    ]

    operations = []
