# Generated by Django 2.2.10 on 2020-03-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_job_attachments"),
        ("recruitment", "0016_merge_20200311_1715"),
    ]

    operations = [
        migrations.AddField(
            model_name="talentlinkjob",
            name="attachments",
            field=models.ManyToManyField(
                blank=True, related_name="jobs", to="documents.CustomDocument"
            ),
        ),
    ]
