# Generated by Django 2.2.10 on 2020-03-18 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0016_merge_20200311_1715"),
        ("recruitment", "0013_jobcategory_sort_order"),
    ]

    operations = []
