# Generated by Django 2.2.10 on 2020-03-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0016_merge_20200311_1715"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobcategory",
            name="is_schools_and_early_years",
            field=models.BooleanField(default=False),
        ),
    ]
