# Generated by Django 2.2.10 on 2020-03-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0017_merge_20200318_1104"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobcategory",
            name="is_schools_and_early_years",
            field=models.BooleanField(default=False),
        ),
    ]
