# Generated by Django 2.2.10 on 2020-03-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0017_merge_20200318_1104"),
        ("recruitment", "0013_image_block"),
    ]

    operations = []
