# Generated by Django 2.2.10 on 2020-03-25 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0018_jobcategory_school_and_early_years"),
        ("recruitment", "0018_merge_20200324_1630"),
    ]

    operations = []
