# Generated by Django 2.2.10 on 2020-03-31 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0017_job_attachments"),
        ("recruitment", "0020_job_postcode"),
    ]

    operations = []
