# Generated by Django 2.2.10 on 2020-03-31 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0021_merge_20200331_1503"),
        ("recruitment", "0013_button_block"),
    ]

    operations = []
