# Generated by Django 2.2.10 on 2020-03-31 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0023_auto_20200331_1646"),
        ("recruitment", "0020_jobs_additional_fields"),
    ]

    operations = []
