# Generated by Django 2.2.10 on 2020-04-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0024_merge_20200331_1816"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruitmenthomepage",
            name="show_live_chat_client",
            field=models.BooleanField(
                default=False, help_text="Show live chat support client on this page"
            ),
        ),
        migrations.AddField(
            model_name="recruitmentindexpage",
            name="show_live_chat_client",
            field=models.BooleanField(
                default=False, help_text="Show live chat support client on this page"
            ),
        ),
    ]
