# Generated by Django 2.2.10 on 2020-04-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0025_add_show_live_chat_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="talentlinkjob",
            name="interview_date",
            field=models.DateField(null=True),
        ),
    ]
