# Generated by Django 2.2.10 on 2020-04-14 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0025_add_show_live_chat_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobalertsubscription",
            name="homepage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="recruitment.RecruitmentHomePage",
            ),
        ),
        migrations.AddField(
            model_name="recruitmenthomepage",
            name="job_board",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="talentlinkjob",
            name="homepage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="recruitment.RecruitmentHomePage",
            ),
        ),
    ]
