# Generated by Django 2.2.10 on 2020-04-09 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_job_employer_logo"),
        ("recruitment", "0025_add_show_live_chat_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="talentlinkjob",
            name="logo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.CustomImage",
            ),
        ),
    ]
