# Generated by Django 2.2.10 on 2020-04-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0025_add_show_live_chat_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobcategory",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                help_text="The name of the category as it will appear in search filter e.g /search/category=[my-slug]",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="jobcategory",
            name="title",
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name="jobsubcategory",
            name="title",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
