# Generated by Django 2.2.10 on 2020-04-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0025_add_show_live_chat_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentlinkjob',
            name='job_board',
            field=models.CharField(choices=[('external', 'External'), ('internal', 'Internal')], default='external', max_length=20),
            preserve_default=False,
        ),
    ]
