# Generated by Django 2.2.10 on 2020-04-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0025_add_show_live_chat_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobsubcategory",
            name="title",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
