# Generated by Django 2.2.10 on 2020-04-16 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0026_remove_local_area_links_postscript_field"),
        ("recruitment", "0026_add_interview_date_to_talentlinkjob_table"),
    ]

    operations = []
