# Generated by Django 2.2.10 on 2020-04-17 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0026_job_employer_logo"),
        ("recruitment", "0027_merge_20200416_0617"),
    ]

    operations = []
