# Generated by Django 2.2.10 on 2020-04-16 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0027_merge_20200416_0617"),
    ]

    operations = [
        migrations.RenameField(
            model_name="talentlinkjob",
            old_name="searchable_location",
            new_name="location",
        ),
    ]
