# Generated by Django 2.2.12 on 2020-04-22 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0026_add_jobsubcategory_uniqueness_constraints"),
        ("recruitment", "0028_merge_20200417_1506"),
    ]

    operations = []
