# Generated by Django 2.2.10 on 2020-04-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0028_merge_20200417_1506"),
        ("recruitment", "0028_rename_searchable_location_field_to_location"),
    ]

    operations = []
