# Generated by Django 2.2.12 on 2020-04-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0026_add_jobsubcategory_uniqueness_constraints"),
        ("recruitment", "0029_merge_20200417_1254"),
    ]

    operations = []
