# Generated by Django 2.2.12 on 2020-04-22 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0030_merge_20200422_1407"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobalertsubscription",
            name="homepage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="recruitment.RecruitmentHomePage",
            ),
        ),
        migrations.AddField(
            model_name="recruitmenthomepage",
            name="job_board",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name="talentlinkjob",
            name="homepage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="recruitment.RecruitmentHomePage",
            ),
        ),
    ]
