# Generated by Django 2.2.12 on 2020-04-29 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0032_set_default_job_homepage"),
        ("recruitment", "0031_add_subheading_block"),
    ]

    operations = []
