# Generated by Django 2.2.10 on 2020-05-04 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0033_merge_20200429_1411'),
        ('recruitment', '0032_add_accordion_detail_to_storyblock'),
    ]

    operations = [
    ]
