# Generated by Django 2.2.13 on 2020-09-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0035_add_detail_to_storyblock"),
    ]

    operations = [
        migrations.AddField(
            model_name="talentlinkjob",
            name="organisation",
            field=models.TextField(blank=True),
        ),
    ]
