# Generated by Django 2.2.13 on 2020-09-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0036_add_job_organisation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="talentlinkjob", old_name="location", new_name="location_name",
        ),
        migrations.AddField(
            model_name="talentlinkjob",
            name="location_city",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="talentlinkjob",
            name="location_country",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="talentlinkjob",
            name="location_region",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="talentlinkjob",
            name="location_street",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="talentlinkjob",
            name="location_street_number",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
