# Generated by Django 2.2.13 on 2020-10-07 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0037_change_job_location_fields"),
        ("recruitment", "0036_update_listing_summary_help_text"),
    ]

    operations = []
