# Generated by Django 2.2.13 on 2020-11-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0039_add_highlight_block"),
        ("recruitment", "0039_streamfield_image_alt_text"),
    ]

    operations = []
