# Generated by Django 3.2.9 on 2022-05-04 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0049_add_inset_text_block"),
        ("recruitment", "0049_aligned_columns_data_migration"),
    ]

    operations = []
