# Generated by Django 3.2.9 on 2022-06-14 10:34

from django.db import migrations, models


def migrate_from_choicefield_to_boolean(apps, schema_editor):
    TalentLinkJob = apps.get_model("recruitment", "TalentLinkJob")
    TalentLinkJob.objects.filter(dbs_check_level="No").update(dbs_check=False)
    TalentLinkJob.objects.exclude(dbs_check_level="No").update(dbs_check=True)


def migrate_from_boolean_to_choicefield(apps, schema_editor):
    TalentLinkJob = apps.get_model("recruitment", "TalentLinkJob")
    TalentLinkJob.objects.filter(dbs_check=False).update(dbs_check_level="No")
    TalentLinkJob.objects.filter(dbs_check=True).update(dbs_check_level="Enhanced DBS")


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0051_alter_recruitmentindexpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="talentlinkjob",
            name="dbs_check_level",
            field=models.TextField(
                default="No", verbose_name="Does the role require a DBS check?"
            ),
        ),
        migrations.RunPython(
            migrate_from_boolean_to_choicefield, migrate_from_choicefield_to_boolean
        ),
        migrations.RemoveField(
            model_name="talentlinkjob",
            name="dbs_check",
        ),
        migrations.RenameField(
            model_name="talentlinkjob",
            old_name="dbs_check_level",
            new_name="dbs_check",
        ),
    ]
