# Generated by Django 3.2.13 on 2023-01-31 09:35

from django.db import migrations, models

from bc.utils.choices import IconChoice


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0055_required_listing_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobcategory",
            name="icon",
            field=models.CharField(
                blank=True,
                # this lambda will always match the current state
                # of IconChoice.choices, and so will not generate a
                # new migration if the underlying values change
                choices=IconChoice.choices,
                max_length=20,
            ),
        ),
    ]
