# Generated by Django 3.2.13 on 2023-01-31 14:57

import django.db.models.deletion
from django.db import migrations, models

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0055_required_listing_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="AwardsSnippet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=255)),
                (
                    "awards",
                    wagtail.fields.StreamField(
                        [
                            (
                                "award",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                form_classname="full title",
                                                icon="title",
                                                label="Award title",
                                            ),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(),
                                        ),
                                        (
                                            "url",
                                            wagtail.blocks.URLBlock(required=False),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        use_json_field=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="recruitmenthomepage",
            name="awards",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="recruitment.awardssnippet",
                verbose_name="Awards snippet",
            ),
        ),
    ]
