# Generated by Django 3.2.13 on 2023-02-03 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0057_awards_snippet"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruitmenthomepage",
            name="hero_subtitle",
            field=models.CharField(
                blank=True,
                help_text="e.g. Over 100 job opportunities available daily.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="recruitmenthomepage",
            name="related_recruitment_index_page",
            field=models.ForeignKey(
                help_text="The page whose “top 6” child pages will be displayed as cards on the current page",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="recruitment.recruitmentindexpage",
            ),
        ),
    ]
