# Generated by Django 3.2.13 on 2023-02-03 15:02

import django.db.models.deletion
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0057_awards_snippet"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPlatformsMediaSnippet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                (
                    "cta",
                    models.CharField(
                        max_length=255, verbose_name="Call to action text"
                    ),
                ),
                (
                    "job_platforms",
                    wagtail.fields.StreamField(
                        [
                            (
                                "platform",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                form_classname="full title",
                                                icon="title",
                                                label="Name",
                                            ),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="Logo"
                                            ),
                                        ),
                                        ("url", wagtail.blocks.URLBlock()),
                                    ]
                                ),
                            )
                        ],
                        use_json_field=True,
                    ),
                ),
                (
                    "media_embed",
                    wagtail.fields.StreamField(
                        [
                            (
                                "embed",
                                wagtail.embeds.blocks.EmbedBlock(
                                    help_text="Embed URL, e.g. https://www.youtube.com/watch?v=Js8dIRxwSRY"
                                ),
                            ),
                            (
                                "image_with_link",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(),
                                        ),
                                        (
                                            "url",
                                            wagtail.blocks.URLBlock(
                                                help_text="Link for the image"
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        use_json_field=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="recruitmenthomepage",
            name="media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="recruitment.jobplatformsmediasnippet",
                verbose_name="Job platforms media snippet",
            ),
        ),
    ]
