# Generated by Django 3.2.13 on 2023-02-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0059_add_extra_fields_to_recruitmenthomepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruitmenthomepage",
            name="recruitment_index_link_text",
            field=models.CharField(
                blank=True,
                help_text="e.g. If blank, a default of 'Visit our guide page' will be used",
                max_length=255,
                verbose_name="Related recruitment index page link text",
            ),
        ),
    ]
