# Generated by Django 3.2.13 on 2023-02-17 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0004_wagtail_3_upgrade"),
        ("recruitment", "0060_recruitmenthomepage_recruitment_index_link_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruitmentindexpage",
            name="hero_subtitle",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="recruitmentindexpage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
    ]
