# Generated by Django 3.2.13 on 2023-04-11 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0057_add_help_text_to_plain_tables"),
        (
            "recruitment",
            "0061_recruitmentindexpage_optional_hero_image_and_herosubtitle",
        ),
    ]

    operations = []
