# Generated by Django 3.2.13 on 2022-08-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_job_employer_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customimage",
            name="file_hash",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=40
            ),
        ),
    ]
