# Generated by Django 4.2.10 on 2024-02-23 07:34

import wagtail.images.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0005_wagtail42_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rendition",
            name="file",
            field=wagtail.images.models.WagtailImageField(
                height_field="height",
                storage=wagtail.images.models.get_rendition_storage,
                upload_to=wagtail.images.models.get_rendition_upload_to,
                width_field="width",
            ),
        ),
    ]
