# Generated by Django 4.2.18 on 2025-01-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0006_django_42_upgrade"),
    ]

    operations = [
        migrations.AddField(
            model_name="customimage",
            name="description",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="description"
            ),
        ),
    ]
