# Generated by Django 2.2.13 on 2020-10-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family_information", "0001_squashed_0008_rewrite_family_information_pages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familyinformationhomepage",
            name="banner_description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="familyinformationhomepage",
            name="banner_link",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="familyinformationhomepage",
            name="banner_title",
            field=models.TextField(),
        ),
    ]
