# Generated by Django 3.2.13 on 2022-10-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family_information", "0004_rename_familyinformationhomepage_subsitehomepage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorytypeonepage",
            name="listing_summary",
            field=models.CharField(
                help_text="The text summary used when this page appears in listings. It's also used as the description for search engines if the 'Meta description' field above is not defined.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="categorytypetwopage",
            name="listing_summary",
            field=models.CharField(
                help_text="The text summary used when this page appears in listings. It's also used as the description for search engines if the 'Meta description' field above is not defined.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="subsitehomepage",
            name="listing_summary",
            field=models.CharField(
                help_text="The text summary used when this page appears in listings. It's also used as the description for search engines if the 'Meta description' field above is not defined.",
                max_length=255,
            ),
        ),
    ]
