# Generated by Django 2.2.12 on 2020-05-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family_information", "0004_auto_20200512_2343"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usefullinks",
            name="lede",
            field=models.TextField(),
        ),
    ]
