# Generated by Django 3.2.13 on 2022-11-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family_information", "0005_required_listing_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="subsitehomepage",
            name="search_prompt_text",
            field=models.TextField(
                blank=True, help_text="Text to prompt user to search"
            ),
        ),
    ]
