# Generated by Django 3.2.13 on 2022-11-07 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0004_wagtail_3_upgrade"),
        ("family_information", "0006_subsitehomepage_search_prompt_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorytypeonepage",
            name="banner_description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="categorytypeonepage",
            name="banner_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
        migrations.AlterField(
            model_name="categorytypeonepage",
            name="banner_link",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="categorytypeonepage",
            name="banner_title",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="categorytypetwopage",
            name="banner_description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="categorytypetwopage",
            name="banner_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
        migrations.AlterField(
            model_name="categorytypetwopage",
            name="banner_link",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="categorytypetwopage",
            name="banner_title",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="subsitehomepage",
            name="banner_description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="subsitehomepage",
            name="banner_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
        migrations.AlterField(
            model_name="subsitehomepage",
            name="banner_link",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="subsitehomepage",
            name="banner_title",
            field=models.TextField(blank=True),
        ),
    ]
