# Generated by Django 2.2.13 on 2020-10-13 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family_information", "0006_familyinformationhomepage_links_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familyinformationhomepage",
            name="left_action",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.Page",
            ),
        ),
        migrations.AlterField(
            model_name="familyinformationhomepage",
            name="right_action",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.Page",
            ),
        ),
    ]
