# Generated by Django 2.2.13 on 2020-10-27 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0045_assign_unlock_grouppagepermission"),
        ("images", "0003_job_employer_logo"),
        ("family_information", "0007_set_null_on_link_page_deletion"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryTypeOnePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                ("banner_title", models.TextField()),
                ("banner_description", models.TextField()),
                ("banner_link", models.URLField()),
                ("banner_link_text", models.CharField(blank=True, max_length=100)),
                (
                    "banner_image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.CustomImage",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="CategoryTypeTwoPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                ("banner_title", models.TextField()),
                ("banner_description", models.TextField()),
                ("banner_link", models.URLField()),
                ("banner_link_text", models.CharField(blank=True, max_length=100)),
                (
                    "banner_image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.CustomImage",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.RemoveField(
            model_name="familyinformationhomepage", name="left_action",
        ),
        migrations.RemoveField(
            model_name="familyinformationhomepage", name="left_label",
        ),
        migrations.RemoveField(
            model_name="familyinformationhomepage", name="left_lede",
        ),
        migrations.RemoveField(
            model_name="familyinformationhomepage", name="left_title",
        ),
        migrations.RemoveField(
            model_name="familyinformationhomepage", name="links_image",
        ),
        migrations.RemoveField(
            model_name="familyinformationhomepage", name="right_action",
        ),
        migrations.RemoveField(
            model_name="familyinformationhomepage", name="right_label",
        ),
        migrations.RemoveField(
            model_name="familyinformationhomepage", name="right_lede",
        ),
        migrations.RemoveField(
            model_name="familyinformationhomepage", name="right_title",
        ),
        migrations.AddField(
            model_name="familyinformationhomepage",
            name="banner_description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="familyinformationhomepage",
            name="banner_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.CustomImage",
            ),
        ),
        migrations.AddField(
            model_name="familyinformationhomepage",
            name="banner_link",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="familyinformationhomepage",
            name="banner_link_text",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="familyinformationhomepage",
            name="banner_title",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="familyinformationhomepage",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="familyinformationhomepage",
            name="search_placeholder",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="familyinformationhomepage",
            name="listing_summary",
            field=models.CharField(
                blank=True,
                help_text="The text summary used when this page appears in listings. It's also used as the description for search engines if the 'Meta description' field above is not defined.",
                max_length=255,
            ),
        ),
        migrations.DeleteModel(name="UsefulLinks",),
    ]
