# Generated by Django 3.2.13 on 2022-11-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family_information", "0008_categorypage"),
    ]

    operations = [
        migrations.AddField(
            model_name="subsitehomepage",
            name="is_pensions_site",
            field=models.BooleanField(default=False),
        ),
    ]
