# Generated by Django 3.2.13 on 2023-01-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family_information", "0009_subsitehomepage_is_pensions_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="subsitehomepage",
            name="heading",
            field=models.CharField(
                blank=True,
                default="Get information, advice and guidance",
                max_length=255,
            ),
        ),
    ]
