# Generated by Django 4.2.11 on 2024-06-27 18:41

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("family_information", "0010_subsitehomepage_heading"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorypage",
            name="fis_directory_widget",
            field=wagtail.fields.StreamField(
                [
                    (
                        "fis_directory_widget",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Title of the widget", required=True
                                    ),
                                ),
                                (
                                    "search_placeholder",
                                    wagtail.blocks.CharBlock(
                                        help_text="Placeholder text for the search input",
                                        required=False,
                                    ),
                                ),
                                (
                                    "directory",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("send", "send"),
                                            ("familyinfo", "familyinfo"),
                                        ],
                                        help_text="Which directory to search",
                                    ),
                                ),
                                (
                                    "extra_query_params",
                                    wagtail.blocks.CharBlock(
                                        help_text="Extra query parameters to add to the search",
                                        required=False,
                                    ),
                                ),
                            ],
                            template="patterns/organisms/search-widget/search-widget.html",
                        ),
                    )
                ],
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="categorytypeonepage",
            name="fis_directory_widget",
            field=wagtail.fields.StreamField(
                [
                    (
                        "fis_directory_widget",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Title of the widget", required=True
                                    ),
                                ),
                                (
                                    "search_placeholder",
                                    wagtail.blocks.CharBlock(
                                        help_text="Placeholder text for the search input",
                                        required=False,
                                    ),
                                ),
                                (
                                    "directory",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("send", "send"),
                                            ("familyinfo", "familyinfo"),
                                        ],
                                        help_text="Which directory to search",
                                    ),
                                ),
                                (
                                    "extra_query_params",
                                    wagtail.blocks.CharBlock(
                                        help_text="Extra query parameters to add to the search",
                                        required=False,
                                    ),
                                ),
                            ],
                            template="patterns/organisms/search-widget/search-widget.html",
                        ),
                    )
                ],
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="categorytypetwopage",
            name="fis_directory_widget",
            field=wagtail.fields.StreamField(
                [
                    (
                        "fis_directory_widget",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Title of the widget", required=True
                                    ),
                                ),
                                (
                                    "search_placeholder",
                                    wagtail.blocks.CharBlock(
                                        help_text="Placeholder text for the search input",
                                        required=False,
                                    ),
                                ),
                                (
                                    "directory",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("send", "send"),
                                            ("familyinfo", "familyinfo"),
                                        ],
                                        help_text="Which directory to search",
                                    ),
                                ),
                                (
                                    "extra_query_params",
                                    wagtail.blocks.CharBlock(
                                        help_text="Extra query parameters to add to the search",
                                        required=False,
                                    ),
                                ),
                            ],
                            template="patterns/organisms/search-widget/search-widget.html",
                        ),
                    )
                ],
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="subsitehomepage",
            name="fis_directory_widget",
            field=wagtail.fields.StreamField(
                [
                    (
                        "fis_directory_widget",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Title of the widget", required=True
                                    ),
                                ),
                                (
                                    "search_placeholder",
                                    wagtail.blocks.CharBlock(
                                        help_text="Placeholder text for the search input",
                                        required=False,
                                    ),
                                ),
                                (
                                    "directory",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("send", "send"),
                                            ("familyinfo", "familyinfo"),
                                        ],
                                        help_text="Which directory to search",
                                    ),
                                ),
                                (
                                    "extra_query_params",
                                    wagtail.blocks.CharBlock(
                                        help_text="Extra query parameters to add to the search",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
            ),
        ),
    ]
