# Generated by Django 4.2.11 on 2024-06-07 07:54

import django.db.models.deletion
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family_information", "0010_subsitehomepage_heading"),
    ]

    operations = [
        migrations.CreateModel(
            name="EHCCo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "verbose_name": "EHCCo",
                "verbose_name_plural": "EHCCos",
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                (
                    "hub_email",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "sencsb@buckinghamshire.gov.uk",
                                "sencsb@buckinghamshire.gov.uk",
                            ),
                            (
                                "senwycombe@buckinghamshire.gov.uk",
                                "senwycombe@buckinghamshire.gov.uk",
                            ),
                            (
                                "Senaylesbury@buckinghamshire.gov.uk",
                                "Senaylesbury@buckinghamshire.gov.uk",
                            ),
                        ],
                    ),
                ),
                (
                    "ehc_co",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schools",
                        to="family_information.ehcco",
                    ),
                ),
            ],
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
