# Generated by Django 4.2.11 on 2024-06-14 09:20

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("family_information", "0010_subsitehomepage_heading"),
    ]

    operations = [
        migrations.AddField(
            model_name="subsitehomepage",
            name="highlighted_cards",
            field=wagtail.fields.StreamField(
                [
                    (
                        "two_card_row",
                        wagtail.blocks.StreamBlock(
                            [("card", wagtail.blocks.PageChooserBlock())]
                        ),
                    ),
                    (
                        "three_card_row",
                        wagtail.blocks.StreamBlock(
                            [("card", wagtail.blocks.PageChooserBlock())]
                        ),
                    ),
                ],
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="subsitehomepage",
            name="top_tasks_heading",
            field=models.CharField(default="What do you want to do?", max_length=255),
        ),
        migrations.CreateModel(
            name="SubsiteHomePageTopTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "source",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="top_tasks",
                        to="family_information.subsitehomepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
