# Generated by Django 4.2.11 on 2024-06-14 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0014_toptask"),
        ("family_information", "0011_subsitehomepage_highlighted_cards_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subsitehomepagetoptask",
            name="top_task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="utils.toptask",
            ),
        ),
    ]
