# Generated by Django 4.2.11 on 2024-06-18 11:35

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0014_toptask"),
        ("family_information", "0012_subsitehomepagetoptask_top_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorypage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.blocks.CharBlock(
                            icon="title",
                            template="patterns/molecules/streamfield/blocks/heading_block.html",
                        ),
                    ),
                    (
                        "cards",
                        wagtail.blocks.StreamBlock(
                            [("card", wagtail.blocks.PageChooserBlock())]
                        ),
                    ),
                ],
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="categorypage",
            name="top_tasks_heading",
            field=models.CharField(default="What do you want to do?", max_length=255),
        ),
        migrations.AddField(
            model_name="categorypage",
            name="other_pages_heading",
            field=models.CharField(default="Others", max_length=255),
        ),
        migrations.AddField(
            model_name="categorytypeonepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.blocks.CharBlock(
                            icon="title",
                            template="patterns/molecules/streamfield/blocks/heading_block.html",
                        ),
                    ),
                    (
                        "cards",
                        wagtail.blocks.StreamBlock(
                            [("card", wagtail.blocks.PageChooserBlock())]
                        ),
                    ),
                ],
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="categorytypeonepage",
            name="top_tasks_heading",
            field=models.CharField(default="What do you want to do?", max_length=255),
        ),
        migrations.AddField(
            model_name="categorytypeonepage",
            name="other_pages_heading",
            field=models.CharField(default="Others", max_length=255),
        ),
        migrations.AddField(
            model_name="categorytypetwopage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.blocks.CharBlock(
                            icon="title",
                            template="patterns/molecules/streamfield/blocks/heading_block.html",
                        ),
                    ),
                    (
                        "cards",
                        wagtail.blocks.StreamBlock(
                            [("card", wagtail.blocks.PageChooserBlock())]
                        ),
                    ),
                ],
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="categorytypetwopage",
            name="top_tasks_heading",
            field=models.CharField(default="What do you want to do?", max_length=255),
        ),
        migrations.AddField(
            model_name="categorytypetwopage",
            name="other_pages_heading",
            field=models.CharField(default="Others", max_length=255),
        ),
        migrations.CreateModel(
            name="CategoryTypeTwoPageTopTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "source",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="top_tasks",
                        to="family_information.categorytypetwopage",
                    ),
                ),
                (
                    "top_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="utils.toptask",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CategoryTypeOnePageTopTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "source",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="top_tasks",
                        to="family_information.categorytypeonepage",
                    ),
                ),
                (
                    "top_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="utils.toptask",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CategoryPageTopTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "source",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="top_tasks",
                        to="family_information.categorypage",
                    ),
                ),
                (
                    "top_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="utils.toptask",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
