# Generated by Django 4.2.11 on 2024-07-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("family_information", "0011_add_school_and_ehcco_models"),
        ("family_information", "0012_subsitehomepagetoptask_top_task"),
    ]

    operations = []
