# Generated by Django 4.2.11 on 2024-07-09 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "family_information",
            "0013_categorypage_body_categorypage_top_tasks_heading_and_more",
        ),
        ("family_information", "0013_merge_20240709_1253"),
    ]

    operations = []
