# Generated by Django 4.2.14 on 2024-07-25 15:10

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("family_information", "0015_add_directory_search_block"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorypage",
            name="directory_search",
            field=wagtail.fields.StreamField(
                [
                    (
                        "directory_search",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Title of the widget", required=True
                                    ),
                                ),
                                (
                                    "search_placeholder",
                                    wagtail.blocks.CharBlock(
                                        help_text="Placeholder text for the search input",
                                        required=False,
                                    ),
                                ),
                                (
                                    "directory",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            (
                                                "bucks_online_directory",
                                                "Bucks Online Directory",
                                            ),
                                            (
                                                "familyinfo",
                                                "Family Information Service",
                                            ),
                                            ("send", "SEND"),
                                        ],
                                        help_text="Which directory to search",
                                    ),
                                ),
                                (
                                    "extra_query_params",
                                    wagtail.blocks.CharBlock(
                                        help_text="Extra query parameters to add to the search, e.g. ?collection=things-to-do&needs=autism",
                                        required=False,
                                    ),
                                ),
                            ],
                            template="patterns/organisms/search-widget/search-widget.html",
                        ),
                    )
                ],
                blank=True,
            ),
        ),
        migrations.AlterField(
            model_name="categorypage",
            name="other_pages_heading",
            field=models.CharField(blank=True, default="Others", max_length=255),
        ),
        migrations.AlterField(
            model_name="categorytypeonepage",
            name="directory_search",
            field=wagtail.fields.StreamField(
                [
                    (
                        "directory_search",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Title of the widget", required=True
                                    ),
                                ),
                                (
                                    "search_placeholder",
                                    wagtail.blocks.CharBlock(
                                        help_text="Placeholder text for the search input",
                                        required=False,
                                    ),
                                ),
                                (
                                    "directory",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            (
                                                "bucks_online_directory",
                                                "Bucks Online Directory",
                                            ),
                                            (
                                                "familyinfo",
                                                "Family Information Service",
                                            ),
                                            ("send", "SEND"),
                                        ],
                                        help_text="Which directory to search",
                                    ),
                                ),
                                (
                                    "extra_query_params",
                                    wagtail.blocks.CharBlock(
                                        help_text="Extra query parameters to add to the search, e.g. ?collection=things-to-do&needs=autism",
                                        required=False,
                                    ),
                                ),
                            ],
                            template="patterns/organisms/search-widget/search-widget.html",
                        ),
                    )
                ],
                blank=True,
            ),
        ),
        migrations.AlterField(
            model_name="categorytypeonepage",
            name="other_pages_heading",
            field=models.CharField(blank=True, default="Others", max_length=255),
        ),
        migrations.AlterField(
            model_name="categorytypetwopage",
            name="directory_search",
            field=wagtail.fields.StreamField(
                [
                    (
                        "directory_search",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Title of the widget", required=True
                                    ),
                                ),
                                (
                                    "search_placeholder",
                                    wagtail.blocks.CharBlock(
                                        help_text="Placeholder text for the search input",
                                        required=False,
                                    ),
                                ),
                                (
                                    "directory",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            (
                                                "bucks_online_directory",
                                                "Bucks Online Directory",
                                            ),
                                            (
                                                "familyinfo",
                                                "Family Information Service",
                                            ),
                                            ("send", "SEND"),
                                        ],
                                        help_text="Which directory to search",
                                    ),
                                ),
                                (
                                    "extra_query_params",
                                    wagtail.blocks.CharBlock(
                                        help_text="Extra query parameters to add to the search, e.g. ?collection=things-to-do&needs=autism",
                                        required=False,
                                    ),
                                ),
                            ],
                            template="patterns/organisms/search-widget/search-widget.html",
                        ),
                    )
                ],
                blank=True,
            ),
        ),
        migrations.AlterField(
            model_name="categorytypetwopage",
            name="other_pages_heading",
            field=models.CharField(blank=True, default="Others", max_length=255),
        ),
        migrations.AlterField(
            model_name="subsitehomepage",
            name="directory_search",
            field=wagtail.fields.StreamField(
                [
                    (
                        "directory_search",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Title of the widget", required=True
                                    ),
                                ),
                                (
                                    "search_placeholder",
                                    wagtail.blocks.CharBlock(
                                        help_text="Placeholder text for the search input",
                                        required=False,
                                    ),
                                ),
                                (
                                    "directory",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            (
                                                "bucks_online_directory",
                                                "Bucks Online Directory",
                                            ),
                                            (
                                                "familyinfo",
                                                "Family Information Service",
                                            ),
                                            ("send", "SEND"),
                                        ],
                                        help_text="Which directory to search",
                                    ),
                                ),
                                (
                                    "extra_query_params",
                                    wagtail.blocks.CharBlock(
                                        help_text="Extra query parameters to add to the search, e.g. ?collection=things-to-do&needs=autism",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
            ),
        ),
    ]
