# Generated by Django 4.2.14 on 2024-08-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "family_information",
            "0016_directory_search_block__add_bucks_online_directory_option",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="categorypage",
            name="display_featured_images",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="categorytypeonepage",
            name="display_featured_images",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="categorytypetwopage",
            name="display_featured_images",
            field=models.BooleanField(default=False),
        ),
    ]
