# Generated by Django 2.2.9 on 2019-12-19 22:10

import django.db.models.deletion
from django.db import migrations, models

import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
    ]

    operations = [
        migrations.CreateModel(
            name="InlineIndex",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        default="Introduction",
                        help_text="Title that appears on the index. (e.g. Introduction)",
                        max_length=255,
                    ),
                ),
                (
                    "body",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "heading",
                                wagtail.core.blocks.CharBlock(
                                    classname="full title",
                                    icon="title",
                                    template="patterns/molecules/streamfield/blocks/heading_block.html",
                                ),
                            ),
                            (
                                "paragraph",
                                wagtail.core.blocks.RichTextBlock(
                                    features=[
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "link",
                                        "document-link",
                                    ]
                                ),
                            ),
                            (
                                "local_area_links",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "introduction",
                                            wagtail.core.blocks.RichTextBlock(
                                                default="<p>Select your local area for information:</p>",
                                                features=[
                                                    "bold",
                                                    "italic",
                                                    "ol",
                                                    "ul",
                                                    "link",
                                                    "document-link",
                                                ],
                                            ),
                                        ),
                                        (
                                            "aylesbury_vale_url",
                                            wagtail.core.blocks.URLBlock(
                                                label="Aylesbury Vale URL",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "chiltern_url",
                                            wagtail.core.blocks.URLBlock(
                                                label="Chiltern URL", required=False
                                            ),
                                        ),
                                        (
                                            "south_bucks_url",
                                            wagtail.core.blocks.URLBlock(
                                                label="South Bucks URL", required=False
                                            ),
                                        ),
                                        (
                                            "wycombe_url",
                                            wagtail.core.blocks.URLBlock(
                                                label="Wycombe URL", required=False
                                            ),
                                        ),
                                        (
                                            "postscript",
                                            wagtail.core.blocks.RichTextBlock(
                                                default='<p>Or <a href="https://www.gov.uk/find-local-council">click here</a> to find your area based on your postcode.</p>',
                                                features=[
                                                    "bold",
                                                    "italic",
                                                    "ol",
                                                    "ul",
                                                    "link",
                                                    "document-link",
                                                ],
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ]
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="InlineIndexChild",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "body",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "heading",
                                wagtail.core.blocks.CharBlock(
                                    classname="full title",
                                    icon="title",
                                    template="patterns/molecules/streamfield/blocks/heading_block.html",
                                ),
                            ),
                            (
                                "paragraph",
                                wagtail.core.blocks.RichTextBlock(
                                    features=[
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "link",
                                        "document-link",
                                    ]
                                ),
                            ),
                            (
                                "local_area_links",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "introduction",
                                            wagtail.core.blocks.RichTextBlock(
                                                default="<p>Select your local area for information:</p>",
                                                features=[
                                                    "bold",
                                                    "italic",
                                                    "ol",
                                                    "ul",
                                                    "link",
                                                    "document-link",
                                                ],
                                            ),
                                        ),
                                        (
                                            "aylesbury_vale_url",
                                            wagtail.core.blocks.URLBlock(
                                                label="Aylesbury Vale URL",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "chiltern_url",
                                            wagtail.core.blocks.URLBlock(
                                                label="Chiltern URL", required=False
                                            ),
                                        ),
                                        (
                                            "south_bucks_url",
                                            wagtail.core.blocks.URLBlock(
                                                label="South Bucks URL", required=False
                                            ),
                                        ),
                                        (
                                            "wycombe_url",
                                            wagtail.core.blocks.URLBlock(
                                                label="Wycombe URL", required=False
                                            ),
                                        ),
                                        (
                                            "postscript",
                                            wagtail.core.blocks.RichTextBlock(
                                                default='<p>Or <a href="https://www.gov.uk/find-local-council">click here</a> to find your area based on your postcode.</p>',
                                                features=[
                                                    "bold",
                                                    "italic",
                                                    "ol",
                                                    "ul",
                                                    "link",
                                                    "document-link",
                                                ],
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ]
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("wagtailcore.page",),
        ),
    ]
