# Generated by Django 2.2.7 on 2020-01-03 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_customimage_file_hash"),
        ("inlineindex", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inlineindex",
            name="listing_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Choose the image you wish to be displayed when this page appears in listings",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.CustomImage",
            ),
        ),
        migrations.AddField(
            model_name="inlineindex",
            name="listing_summary",
            field=models.CharField(
                blank=True,
                help_text="The text summary used when this page appears in listings. It's also used as the description for search engines if the 'Search description' field above is not defined.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="inlineindex",
            name="listing_title",
            field=models.CharField(
                blank=True,
                help_text="Override the page title used when this page appears in listings",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="inlineindex",
            name="social_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.CustomImage",
            ),
        ),
        migrations.AddField(
            model_name="inlineindex",
            name="social_text",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="inlineindexchild",
            name="listing_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Choose the image you wish to be displayed when this page appears in listings",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.CustomImage",
            ),
        ),
        migrations.AddField(
            model_name="inlineindexchild",
            name="listing_summary",
            field=models.CharField(
                blank=True,
                help_text="The text summary used when this page appears in listings. It's also used as the description for search engines if the 'Search description' field above is not defined.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="inlineindexchild",
            name="listing_title",
            field=models.CharField(
                blank=True,
                help_text="Override the page title used when this page appears in listings",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="inlineindexchild",
            name="social_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.CustomImage",
            ),
        ),
        migrations.AddField(
            model_name="inlineindexchild",
            name="social_text",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
