# Generated by Django 2.2.13 on 2020-11-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inlineindex", "0016_inlineindexrelatedpage"),
        ("inlineindex", "0015_streamfield_image_alt_text"),
    ]

    operations = []
