# Generated by Django 3.2.9 on 2022-01-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inlineindex", "0023_typedtableblock_data_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="inlineindex",
            name="intro_text",
            field=models.TextField(blank=True),
        ),
    ]
