# Generated by Django 3.2.9 on 2022-05-12 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inlineindex", "0024_inlineindex_intro_text"),
        ("inlineindex", "0027_auto_20220504_1323"),
    ]

    operations = []
