# Generated by Django 2.2.10 on 2020-03-25 12:06

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apteanrespondcaseformpage",
            old_name="thank_you_text",
            new_name="completion_content",
        ),
        migrations.AddField(
            model_name="apteanrespondcaseformpage",
            name="completion_title",
            field=models.CharField(
                default="",
                help_text="Heading for the page show after successful form submission.",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="apteanrespondcaseformpage",
            name="pre_submission_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Text displayed after the form, above the submit button",
                verbose_name="pre-submission text",
            ),
        ),
        migrations.AlterField(
            model_name="apteanrespondcaseformpage",
            name="action_text",
            field=models.CharField(
                blank=True,
                help_text='Form action button text. Defaults to "Submit"',
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="apteanrespondcaseformpage",
            name="web_service_definition",
            field=models.CharField(
                choices=[("TestCreateComplaints", "TestCreateComplaints")],
                help_text="The name of the CreateCase web service to use.",
                max_length=255,
            ),
        ),
    ]
