# Generated by Django 2.2.10 on 2020-03-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_update_case_form_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apteanrespondcaseformpage",
            name="web_service_definition",
            field=models.CharField(
                help_text="The name of the CreateCase web service to use.",
                max_length=255,
            ),
        ),
    ]
