# Generated by Django 2.2.12 on 2020-05-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_add_show_live_chat_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="apteanrespondcaseformpage",
            name="form",
            field=models.CharField(
                blank=True,
                choices=[
                    ("complaint", "Complaint"),
                    ("foi", "FOI"),
                    ("sar", "SAR"),
                    ("comments", "Comments"),
                    ("compliments", "Compliments"),
                    ("disclosures", "Disclosures"),
                ],
                max_length=255,
            ),
        ),
    ]
