# Generated by Django 2.2.12 on 2020-05-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0006_convert_web_services_to_form_names"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apteanrespondcaseformpage",
            name="web_service_definition",
        ),
        migrations.AlterField(
            model_name="apteanrespondcaseformpage",
            name="form",
            field=models.CharField(
                choices=[
                    ("complaint", "Complaint"),
                    ("foi", "FOI"),
                    ("sar", "SAR"),
                    ("comments", "Comments"),
                    ("compliments", "Compliments"),
                    ("disclosures", "Disclosures"),
                ],
                max_length=255,
            ),
        ),
    ]
