# Generated by Django 4.2.14 on 2024-08-07 08:58

from django.db import migrations, models
import django.db.models.deletion
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DirectoryManagementAPI",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admin_name", models.CharField(max_length=128)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "api_url",
                    models.URLField(
                        help_text='The URL of the directory management API is available at, for example: "https://manage-directory-listing.buckinghamshire.gov.uk/api/v1"',
                        verbose_name="API URL",
                    ),
                ),
            ],
            options={
                "verbose_name": "directory management API",
            },
        ),
        migrations.CreateModel(
            name="Taxonomy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("level", models.IntegerField()),
                ("remote_id", models.BigIntegerField(verbose_name="remote ID")),
                ("remote_slug", models.CharField(max_length=255)),
                (
                    "fetched_with",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxonomies",
                        to="service_directory.directorymanagementapi",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_taxonomies",
                        to="service_directory.taxonomy",
                    ),
                ),
            ],
            options={
                "verbose_name": "service directory taxonomy",
                "verbose_name_plural": "service directory taxonomies",
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name="ServiceDirectory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frontend_url",
                    models.URLField(
                        help_text='The URL for users use to access the directory interface, for example: "https://directory.familyinfo.buckinghamshire.gov.uk/". This is used to generate links to the directory services',
                        verbose_name="frontend interface URL",
                    ),
                ),
                ("admin_name", models.CharField(max_length=128)),
                (
                    "directory_api_url",
                    models.URLField(
                        help_text='The URL of the specific directory API is available at, for example: "https://api.familyinfo.buckinghamshire.gov.uk/api/v1"',
                        verbose_name="directory API URL",
                    ),
                ),
                (
                    "directory_api_slug",
                    models.CharField(
                        help_text='Slug used to identify this directory in the directory API, for example: "bfis"',
                        max_length=255,
                        verbose_name="directory API slug",
                    ),
                ),
                (
                    "directory_management_api",
                    models.ForeignKey(
                        help_text="Directory management API used to fetch taxonomies for use with this directory",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="service_directory.directorymanagementapi",
                        verbose_name="directory management API",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "service directories",
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.AddConstraint(
            model_name="taxonomy",
            constraint=models.UniqueConstraint(
                fields=("fetched_with", "remote_id"),
                name="unique_remote_id_per_directory_management_api",
            ),
        ),
    ]
