# Generated by Django 2.2.19 on 2021-05-11 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0060_fix_workflow_unique_constraint"),
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackComment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.CharField(
                        max_length=500, verbose_name="What where you doing?"
                    ),
                ),
                (
                    "issue",
                    models.CharField(max_length=500, verbose_name="What went wrong?"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_comments",
                        to="wagtailcore.Page",
                    ),
                ),
            ],
        ),
    ]
