# Generated by Django 2.2.18 on 2021-06-01 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_feedbackcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackcomment",
            name="original_url",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usefulnessfeedback",
            name="original_url",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="feedbackcomment",
            name="page",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedback_comments",
                to="wagtailcore.Page",
            ),
        ),
        migrations.AlterField(
            model_name="usefulnessfeedback",
            name="page",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usefulness_feedback",
                to="wagtailcore.Page",
            ),
        ),
    ]
