# Generated by Django 2.2.18 on 2021-06-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0003_update_url_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usefulnessfeedback",
            name="original_url",
            field=models.URLField(max_length=2048),
        ),
    ]
