# Generated by Django 3.2.13 on 2022-07-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0005_feedback_field_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackcomment",
            name="original_url",
            field=models.URLField(max_length=2048),
        ),
    ]
