# Generated by Django 2.2.13 on 2020-11-30 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0015_streamfield_image_alt_text"),
        ("news", "0015_add_highlight_block"),
    ]

    operations = []
