# Generated by Django 3.2.9 on 2022-05-31 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_job_employer_logo"),
        ("blogs", "0002_blogpostpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloghomepage",
            name="featured_blogpost_image",
            field=models.ForeignKey(
                blank=True,
                help_text="If the page has its own image, it will override any image set here.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
        migrations.AddField(
            model_name="bloghomepage",
            name="featured_blogpost_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="blogs.blogpostpage",
                verbose_name="Page link",
            ),
        ),
    ]
