# Generated by Django 3.2.9 on 2022-06-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0004_add_social_links_bloghomepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpostpage",
            name="intro_text",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
