# Generated by Django 3.2.9 on 2022-06-10 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0066_collection_management_permissions"),
        ("blogs", "0005_blogpostpage_intro_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloghomepage",
            name="about_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Page link",
            ),
        ),
    ]
