# Generated by Django 3.2.9 on 2022-06-17 09:56

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0007_relatedcategories"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpostpage",
            name="categories",
            field=modelcluster.fields.ParentalManyToManyField(
                related_name="related_posts", to="blogs.RelatedCategories"
            ),
        ),
    ]
