# Generated by Django 3.2.13 on 2022-07-25 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0008_bloghomepagecategories"),
        ("blogs", "0009_notificationrecord"),
    ]

    operations = []
