# Generated by Django 4.2.14 on 2024-10-04 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0006_django_42_upgrade"),
        ("wagtailcore", "0093_uploadedfile"),
        ("promotional", "0002_promotionalsiteconfiguration_promotionalcontentpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotionalhomepage",
            name="hero_title",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="promotionalhomepage",
            name="hero_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
        migrations.AddField(
            model_name="promotionalhomepage",
            name="hero_link_page",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="promotionalhomepage",
            name="hero_link_text",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="promotionalhomepage",
            name="hero_text",
            field=models.TextField(blank=True, max_length=1024),
        ),
    ]
