# Generated by Django 4.2.14 on 2024-10-04 16:03

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0093_uploadedfile"),
        ("promotional", "0003_add_homepage_hero_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotionalsiteconfiguration",
            name="primary_cta_link_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="primary CTA link page",
            ),
        ),
        migrations.AddField(
            model_name="promotionalsiteconfiguration",
            name="primary_cta_link_text",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="primary CTA link text"
            ),
        ),
        migrations.AlterField(
            model_name="promotionalsiteconfiguration",
            name="primary_navigation",
            field=wagtail.fields.StreamField(
                [
                    (
                        "primary_navigation_item",
                        wagtail.blocks.StructBlock(
                            [
                                ("page", wagtail.blocks.PageChooserBlock()),
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Leave blank to use the page's own title",
                                        max_length=64,
                                        required=False,
                                    ),
                                ),
                                (
                                    "populate_child_pages",
                                    wagtail.blocks.BooleanBlock(
                                        help='Auto-populated pages with "Show in menus" selected in their "Promote" tab',
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ]
            ),
        ),
    ]
