# Generated by Django 4.2.14 on 2024-10-08 11:38

import bc.promotional.blocks.cards
from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("promotional", "0004_add_primary_cta_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotionalhomepage",
            name="teasers",
            field=wagtail.fields.StreamField(
                [
                    (
                        "link_cards",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "items",
                                    wagtail.blocks.ListBlock(
                                        bc.promotional.blocks.cards.LinkCard, max_num=3
                                    ),
                                )
                            ]
                        ),
                    )
                ],
                blank=True,
            ),
        ),
    ]
