# Generated by Django 4.2.14 on 2024-10-09 09:12

from django.db import migrations
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("promotional", "0005_promotionalhomepage_teasers"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotionalhomepage",
            name="media_with_text_cta",
            field=wagtail.fields.StreamField(
                [
                    (
                        "media_with_text_cta",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(max_length=128)),
                                (
                                    "text",
                                    wagtail.blocks.TextBlock(
                                        max_length=512, required=False
                                    ),
                                ),
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "embed",
                                    wagtail.embeds.blocks.EmbedBlock(
                                        help_text="URL to a YouTube video or another embed",
                                        label="Embed URL",
                                        required=False,
                                    ),
                                ),
                                ("link_page", wagtail.blocks.PageChooserBlock()),
                                ("link_text", wagtail.blocks.CharBlock(max_length=128)),
                            ]
                        ),
                    )
                ],
                blank=True,
                verbose_name="media with text call to action",
            ),
        ),
    ]
