# Generated by Django 4.2.14 on 2024-10-09 11:48

import bc.promotional.blocks.cards
from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("promotional", "0006_promotionalhomepage_media_with_text_cta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotionalhomepage",
            name="teasers",
            field=wagtail.fields.StreamField(
                [
                    (
                        "link_cards",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "items",
                                    wagtail.blocks.ListBlock(
                                        bc.promotional.blocks.cards.LinkCard, max_num=3
                                    ),
                                ),
                                (
                                    "link_page",
                                    wagtail.blocks.PageChooserBlock(required=False),
                                ),
                                (
                                    "link_text",
                                    wagtail.blocks.CharBlock(
                                        max_length=64, required=False
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
            ),
        ),
    ]
