# Generated by Django 4.2.14 on 2024-10-11 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0035_directory_search_block__add_bucks_online_directory_option"),
        ("promotional", "0009_alter_promotionalcontentpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotionalsiteconfiguration",
            name="events_feed",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the events feed page to fetch events from on this site",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="events.eventindexpage",
            ),
        ),
    ]
