# Generated by Django 4.2.14 on 2024-10-15 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0020_directory_search_block__add_bucks_online_directory_option"),
        ("promotional", "0014_alter_promotionalcontentpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotionalhomepage",
            name="recent_blog_posts_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Select blog home page to which fetch recent blog posts from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="blogs.bloghomepage",
            ),
        ),
        migrations.AddField(
            model_name="promotionalhomepage",
            name="recent_blog_posts_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="promotionalhomepage",
            name="recent_blog_posts_view_all_link_text",
            field=models.CharField(
                blank=True, help_text='Defaults to "View all blogs"', max_length=255
            ),
        ),
    ]
