# Generated by Django 4.2.14 on 2024-10-24 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0093_uploadedfile"),
        ("promotional", "0022_add_external_link_to_media_with_text_cta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotionalcontentpage",
            name="hero_link_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AlterField(
            model_name="promotionalcontentpage",
            name="hero_link_text",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
