# Generated by Django 4.2.14 on 2024-10-24 15:14

import bc.promotional.models.configuration
from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("promotional", "0023_alter_promotionalcontentpage_hero_link_page_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotionalsiteconfiguration",
            name="primary_navigation",
            field=wagtail.fields.StreamField(
                [
                    (
                        "primary_navigation_item",
                        wagtail.blocks.StructBlock(
                            [
                                ("page", wagtail.blocks.PageChooserBlock()),
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="If left blank, the page title will be used",
                                        max_length=64,
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "primary_navigation_section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        max_length=64, required=False
                                    ),
                                ),
                                (
                                    "items",
                                    wagtail.blocks.ListBlock(
                                        bc.promotional.models.configuration.PrimaryNavigationSubItem
                                    ),
                                ),
                            ]
                        ),
                    ),
                ]
            ),
        ),
    ]
