# Generated by Django 4.2.19 on 2025-02-24 14:40

import bc.promotional.blocks.cards
import bc.promotional.blocks.cta
import bc.promotional.blocks.explainer
import bc.promotional.blocks.steps
from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("promotional", "0026_alter_promotionalcontentpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotionalcontentpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("subheading", 1),
                    ("paragraph", 2),
                    ("image", 6),
                    ("embed", 7),
                    ("plain_text_table", 8),
                    ("table", 14),
                    ("button", 18),
                    ("highlight", 19),
                    ("inset_text", 20),
                    ("accordion", 45),
                    ("detail", 48),
                    ("link_cards", 51),
                    ("callout_with_image", 60),
                    ("steps", 62),
                    ("media_with_text_cta", 67),
                    ("quote", 68),
                    ("aligned_media_with_text", 70),
                    ("form", 41),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "full title",
                            "group": "Heading",
                            "help_text": 'The link to this heading uses the heading text in lowercase, with no symbols, and with the spaces replaced with hyphens. e.g. "Lorem @ 2 ipsum" becomes "lorem-2-ipsum"',
                            "icon": "title",
                            "label": "Main heading",
                            "template": "patterns/molecules/streamfield/blocks/promo_heading_block.html",
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "full title",
                            "group": "Heading",
                            "help_text": 'The link to this subheading uses the subheading text in lowercase, with no symbols, and with the spaces replaced with hyphens. e.g. "Lorem @ 2 ipsum" becomes "lorem-2-ipsum"',
                            "icon": "title",
                            "template": "patterns/molecules/streamfield/blocks/promo_subheading_block.html",
                        },
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "document-link",
                            ]
                        },
                    ),
                    3: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Describe the information, not the picture. Leave blank if the image is purely decorative. Do not repeat captions or content already on the page.",
                            "required": False,
                        },
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 3), ("alt_text", 4), ("caption", 5)]],
                        {
                            "template": "patterns/molecules/streamfield/blocks/promo_image_block.html"
                        },
                    ),
                    7: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                    8: (
                        "bc.utils.blocks.TableBlock",
                        (),
                        {
                            "group": "Table",
                            "help_text": 'This table will be displayed as plain text on the page.\n    You can add links to individuals cells by using the following\n    syntax: <em>[link text](www.gov.uk)</em>. This will output as\n    <a href="http://www.gov.uk">link text</a></li>',
                        },
                    ),
                    9: ("wagtail.blocks.DecimalBlock", (), {}),
                    10: ("wagtail.blocks.RichTextBlock", (), {}),
                    11: (
                        "wagtail.blocks.StreamBlock",
                        [[("numeric", 9), ("rich_text", 10)]],
                        {},
                    ),
                    12: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("left_aligned_column", 11), ("right_aligned_column", 11)]],
                        {},
                    ),
                    13: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("table", 12), ("caption", 13)]],
                        {"group": "Table"},
                    ),
                    15: ("wagtail.blocks.CharBlock", (), {"form_classname": "title"}),
                    16: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    17: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 15), ("link_url", 16), ("link_page", 17)]],
                        {
                            "template": "patterns/molecules/streamfield/blocks/promo_button_block.html"
                        },
                    ),
                    19: ("bc.utils.blocks.HighlightBlock", (), {}),
                    20: ("bc.utils.blocks.InsetTextBlock", (), {}),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "full title",
                            "icon": "title",
                            "label": "Accordion title",
                        },
                    ),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "full title",
                            "group": "Heading",
                            "help_text": 'The link to this heading uses the heading text in lowercase, with no symbols, and with the spaces replaced with hyphens. e.g. "Lorem @ 2 ipsum" becomes "lorem-2-ipsum"',
                            "icon": "title",
                            "label": "Main heading",
                            "template": "patterns/molecules/streamfield/blocks/heading_block.html",
                        },
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "full title",
                            "group": "Heading",
                            "help_text": 'The link to this subheading uses the subheading text in lowercase, with no symbols, and with the spaces replaced with hyphens. e.g. "Lorem @ 2 ipsum" becomes "lorem-2-ipsum"',
                            "icon": "title",
                            "template": "patterns/molecules/streamfield/blocks/subheading_block.html",
                        },
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 3), ("alt_text", 4), ("caption", 5)]],
                        {},
                    ),
                    25: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "<p><b>Find local information</b></p>",
                            "features": [
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "document-link",
                            ],
                        },
                    ),
                    26: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "<p>While we finish building this new website, we’re keeping some local information on our old council websites</p>",
                            "features": [
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "document-link",
                            ],
                        },
                    ),
                    27: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "<p>Enter your postcode to help us redirect you to the right place.</p>",
                            "features": [
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "document-link",
                            ],
                            "help_text": "The text that appears on top of the postcode lookup input",
                        },
                    ),
                    28: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "<p>Select your local area to help us direct you to the right place:</p>",
                            "features": [
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "document-link",
                            ],
                            "help_text": "The text that appears on top of the list of local area links",
                        },
                    ),
                    29: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Aylesbury Vale URL"},
                    ),
                    30: ("wagtail.blocks.URLBlock", (), {"label": "Chiltern URL"}),
                    31: ("wagtail.blocks.URLBlock", (), {"label": "South Bucks URL"}),
                    32: ("wagtail.blocks.URLBlock", (), {"label": "Wycombe URL"}),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 25),
                                ("introduction", 26),
                                ("postcode_lookup_text", 27),
                                ("area_lookup_text", 28),
                                ("aylesbury_vale_url", 29),
                                ("chiltern_url", 30),
                                ("south_bucks_url", 31),
                                ("wycombe_url", 32),
                            ]
                        ],
                        {},
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 15), ("link_url", 16), ("link_page", 17)]],
                        {},
                    ),
                    35: (
                        "bc.utils.blocks.EHCCoSearchBlock",
                        (),
                        {"label": "EHCCo Search"},
                    ),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title of the widget", "required": True},
                    ),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Placeholder text for the search input",
                            "required": False,
                        },
                    ),
                    38: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bucks_online_directory", "Bucks Online Directory"),
                                ("familyinfo", "Family Information Service"),
                                ("send", "SEND"),
                            ],
                            "help_text": "Which directory to search",
                        },
                    ),
                    39: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Extra query parameters to add to the search, e.g. ?collection=things-to-do&needs=autism",
                            "required": False,
                        },
                    ),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 36),
                                ("search_placeholder", 37),
                                ("directory", 38),
                                ("extra_query_params", 39),
                            ]
                        ],
                        {},
                    ),
                    41: ("bc.forms.blocks.EmbeddedFormBlock", (), {}),
                    42: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("heading", 22),
                                ("subheading", 23),
                                ("paragraph", 2),
                                ("image", 24),
                                ("embed", 7),
                                ("local_area_links", 33),
                                ("plain_text_table", 8),
                                ("table", 14),
                                ("button", 34),
                                ("highlight", 19),
                                ("inset_text", 20),
                                ("ehc_co_search", 35),
                                ("directory_search", 40),
                                ("form", 41),
                            ]
                        ],
                        {"label": "Accordion content"},
                    ),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 21), ("content", 42)]],
                        {},
                    ),
                    44: (
                        "wagtail.blocks.ListBlock",
                        (43,),
                        {"label": "Accordion items"},
                    ),
                    45: ("wagtail.blocks.StructBlock", [[("items", 44)]], {}),
                    46: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "full title",
                            "icon": "title",
                            "label": "Detail title",
                        },
                    ),
                    47: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "document-link",
                            ],
                            "label": "Detail content",
                        },
                    ),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 46), ("content", 47)]],
                        {},
                    ),
                    49: (
                        "wagtail.blocks.ListBlock",
                        (bc.promotional.blocks.cards.LinkCard,),
                        {"max_num": 3},
                    ),
                    50: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 64, "required": False},
                    ),
                    51: (
                        "wagtail.blocks.StructBlock",
                        [[("items", 49), ("link_page", 17), ("link_text", 50)]],
                        {},
                    ),
                    52: ("wagtail.blocks.CharBlock", (), {"max_length": 128}),
                    53: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"max_length": 1024, "required": False},
                    ),
                    54: ("wagtail.blocks.URLBlock", (), {}),
                    55: ("wagtail.blocks.CharBlock", (), {}),
                    56: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 54), ("title", 55)]],
                        {},
                    ),
                    57: ("wagtail.blocks.PageChooserBlock", (), {}),
                    58: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 57), ("title", 5)]],
                        {},
                    ),
                    59: (
                        "wagtail.blocks.StreamBlock",
                        [[("external_link", 56), ("internal_link", 58)]],
                        {"max_num": 1, "required": False},
                    ),
                    60: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 52), ("text", 53), ("image", 3), ("link", 59)]],
                        {},
                    ),
                    61: (
                        "wagtail.blocks.ListBlock",
                        (bc.promotional.blocks.steps.Step,),
                        {"min_num": 1},
                    ),
                    62: ("wagtail.blocks.StructBlock", [[("steps", 61)]], {}),
                    63: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"max_length": 512, "required": False},
                    ),
                    64: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "URL to a YouTube video or another embed",
                            "label": "Embed URL",
                            "required": False,
                        },
                    ),
                    65: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Please specify the URL or an internal page, not both at the same time",
                            "label": "Link URL",
                            "required": False,
                        },
                    ),
                    66: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Link text must be populated if a link is specified",
                            "max_length": 128,
                            "required": False,
                        },
                    ),
                    67: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 52),
                                ("text", 63),
                                ("image", 3),
                                ("embed", 64),
                                ("link_page", 17),
                                ("link_url", 65),
                                ("link_text", 66),
                            ]
                        ],
                        {},
                    ),
                    68: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 15), ("attribution", 5)]],
                        {
                            "template": "patterns/molecules/streamfield/blocks/promo_quote_block.html"
                        },
                    ),
                    69: (
                        "wagtail.blocks.ListBlock",
                        (bc.promotional.blocks.cta.AlignedMediaWithTextItem,),
                        {"min_num": 1},
                    ),
                    70: ("wagtail.blocks.StructBlock", [[("items", 69)]], {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="promotionalhomepage",
            name="explainer",
            field=wagtail.fields.StreamField(
                [("explainer", 49)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 128}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "full title",
                            "icon": "title",
                            "label": "Accordion title",
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "full title",
                            "group": "Heading",
                            "help_text": 'The link to this heading uses the heading text in lowercase, with no symbols, and with the spaces replaced with hyphens. e.g. "Lorem @ 2 ipsum" becomes "lorem-2-ipsum"',
                            "icon": "title",
                            "label": "Main heading",
                            "template": "patterns/molecules/streamfield/blocks/heading_block.html",
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "full title",
                            "group": "Heading",
                            "help_text": 'The link to this subheading uses the subheading text in lowercase, with no symbols, and with the spaces replaced with hyphens. e.g. "Lorem @ 2 ipsum" becomes "lorem-2-ipsum"',
                            "icon": "title",
                            "template": "patterns/molecules/streamfield/blocks/subheading_block.html",
                        },
                    ),
                    5: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "document-link",
                            ]
                        },
                    ),
                    6: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Describe the information, not the picture. Leave blank if the image is purely decorative. Do not repeat captions or content already on the page.",
                            "required": False,
                        },
                    ),
                    8: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 6), ("alt_text", 7), ("caption", 8)]],
                        {},
                    ),
                    10: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                    11: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "<p><b>Find local information</b></p>",
                            "features": [
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "document-link",
                            ],
                        },
                    ),
                    12: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "<p>While we finish building this new website, we’re keeping some local information on our old council websites</p>",
                            "features": [
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "document-link",
                            ],
                        },
                    ),
                    13: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "<p>Enter your postcode to help us redirect you to the right place.</p>",
                            "features": [
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "document-link",
                            ],
                            "help_text": "The text that appears on top of the postcode lookup input",
                        },
                    ),
                    14: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "<p>Select your local area to help us direct you to the right place:</p>",
                            "features": [
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "document-link",
                            ],
                            "help_text": "The text that appears on top of the list of local area links",
                        },
                    ),
                    15: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Aylesbury Vale URL"},
                    ),
                    16: ("wagtail.blocks.URLBlock", (), {"label": "Chiltern URL"}),
                    17: ("wagtail.blocks.URLBlock", (), {"label": "South Bucks URL"}),
                    18: ("wagtail.blocks.URLBlock", (), {"label": "Wycombe URL"}),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 11),
                                ("introduction", 12),
                                ("postcode_lookup_text", 13),
                                ("area_lookup_text", 14),
                                ("aylesbury_vale_url", 15),
                                ("chiltern_url", 16),
                                ("south_bucks_url", 17),
                                ("wycombe_url", 18),
                            ]
                        ],
                        {},
                    ),
                    20: (
                        "bc.utils.blocks.TableBlock",
                        (),
                        {
                            "group": "Table",
                            "help_text": 'This table will be displayed as plain text on the page.\n    You can add links to individuals cells by using the following\n    syntax: <em>[link text](www.gov.uk)</em>. This will output as\n    <a href="http://www.gov.uk">link text</a></li>',
                        },
                    ),
                    21: ("wagtail.blocks.DecimalBlock", (), {}),
                    22: ("wagtail.blocks.RichTextBlock", (), {}),
                    23: (
                        "wagtail.blocks.StreamBlock",
                        [[("numeric", 21), ("rich_text", 22)]],
                        {},
                    ),
                    24: (
                        "wagtail.contrib.typed_table_block.blocks.TypedTableBlock",
                        [[("left_aligned_column", 23), ("right_aligned_column", 23)]],
                        {},
                    ),
                    25: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("table", 24), ("caption", 25)]],
                        {"group": "Table"},
                    ),
                    27: ("wagtail.blocks.CharBlock", (), {"form_classname": "title"}),
                    28: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    29: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 27), ("link_url", 28), ("link_page", 29)]],
                        {},
                    ),
                    31: ("bc.utils.blocks.HighlightBlock", (), {}),
                    32: ("bc.utils.blocks.InsetTextBlock", (), {}),
                    33: (
                        "bc.utils.blocks.EHCCoSearchBlock",
                        (),
                        {"label": "EHCCo Search"},
                    ),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title of the widget", "required": True},
                    ),
                    35: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Placeholder text for the search input",
                            "required": False,
                        },
                    ),
                    36: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bucks_online_directory", "Bucks Online Directory"),
                                ("familyinfo", "Family Information Service"),
                                ("send", "SEND"),
                            ],
                            "help_text": "Which directory to search",
                        },
                    ),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Extra query parameters to add to the search, e.g. ?collection=things-to-do&needs=autism",
                            "required": False,
                        },
                    ),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 34),
                                ("search_placeholder", 35),
                                ("directory", 36),
                                ("extra_query_params", 37),
                            ]
                        ],
                        {},
                    ),
                    39: ("bc.forms.blocks.EmbeddedFormBlock", (), {}),
                    40: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("heading", 3),
                                ("subheading", 4),
                                ("paragraph", 5),
                                ("image", 9),
                                ("embed", 10),
                                ("local_area_links", 19),
                                ("plain_text_table", 20),
                                ("table", 26),
                                ("button", 30),
                                ("highlight", 31),
                                ("inset_text", 32),
                                ("ehc_co_search", 33),
                                ("directory_search", 38),
                                ("form", 39),
                            ]
                        ],
                        {"label": "Accordion content"},
                    ),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 2), ("content", 40)]],
                        {},
                    ),
                    42: (
                        "wagtail.blocks.ListBlock",
                        (41,),
                        {"label": "Accordion items"},
                    ),
                    43: ("wagtail.blocks.StructBlock", [[("items", 42)]], {}),
                    44: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 128, "required": False},
                    ),
                    45: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"max_length": 512, "required": False},
                    ),
                    46: (
                        "wagtail.blocks.ListBlock",
                        (bc.promotional.blocks.explainer.ExplainerCTALink,),
                        {"max_num": 2, "min_num": 1},
                    ),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("text", 45), ("image", 6), ("links", 46)]],
                        {},
                    ),
                    48: (
                        "wagtail.blocks.StreamBlock",
                        [[("cta", 47)]],
                        {"label": "Call to action", "max_num": 1, "required": False},
                    ),
                    49: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("text", 1),
                                ("details", 43),
                                ("details_link_page", 29),
                                ("details_link_text", 44),
                                ("cta", 48),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
