# Generated by Django 2.2.7 on 2019-12-05 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="navigationsettings", name="footer_navigation",
        ),
        migrations.RemoveField(
            model_name="navigationsettings", name="primary_navigation",
        ),
        migrations.RemoveField(
            model_name="navigationsettings", name="secondary_navigation",
        ),
    ]
