# Generated by Django 2.2.18 on 2021-02-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0004_footer_columns_not_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationsettings',
            name='header_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
