# Generated by Django 2.2.10 on 2020-03-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_customdocument_file_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="customdocument",
            name="talentlink_attachment_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
