# Generated by Django 2.2.7 on 2019-12-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmediasettings",
            name="youtube_channel_url",
            field=models.URLField(blank=True, help_text="Your YouTube channel URL."),
        ),
    ]
