# Generated by Django 2.2.9 on 2020-01-14 14:18

import django.db.models.deletion
from django.db import migrations, models

import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("utils", "0002_add_youtube_channel_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteBannerSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "show_banner",
                    models.BooleanField(
                        default=False,
                        help_text="When set to True, the banner will be displayed on all pages of the site except for homepage. For homepage, please use the alert fields on homepage.",
                    ),
                ),
                ("label", models.CharField(max_length=255, verbose_name="Alert label")),
                ("body", wagtail.core.fields.RichTextField(verbose_name="Text")),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site banner",
            },
        ),
    ]
