# Generated by Django 2.2.13 on 2020-07-20 11:28

from django.db import migrations, models

import bc.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0005_add_cookie_important_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmediasettings",
            name="instagram_username",
            field=models.CharField(
                blank=True, help_text="Your Instagram username.", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="socialmediasettings",
            name="linkedin_organisation_url",
            field=models.CharField(
                blank=True,
                help_text="Your LinkedIn organisation page URL.",
                max_length=255,
                validators=[bc.utils.validators.validate_linkedin_domain],
            ),
        ),
    ]
