# Generated by Django 2.2.13 on 2020-08-11 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0006_delete_sitebannersettings"),
        ("utils", "0006_add_linkedin_and_instagram_settings"),
    ]

    operations = []
