# Generated by Django 4.2.11 on 2024-06-13 04:47

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0013_importantpages_directory_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemmessagessettings",
            name="search_cta_button",
            field=wagtail.fields.StreamField(
                [
                    (
                        "external_link",
                        wagtail.blocks.StructBlock(
                            [
                                ("url", wagtail.blocks.URLBlock()),
                                ("title", wagtail.blocks.CharBlock()),
                            ]
                        ),
                    ),
                    (
                        "internal_link",
                        wagtail.blocks.StructBlock(
                            [
                                ("page", wagtail.blocks.PageChooserBlock()),
                                ("title", wagtail.blocks.CharBlock(required=False)),
                            ]
                        ),
                    ),
                ],
                blank=True,
                verbose_name="Button",
            ),
        ),
        migrations.AddField(
            model_name="systemmessagessettings",
            name="search_cta_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="calltoactionsnippet",
            name="link",
            field=wagtail.fields.StreamField(
                [
                    (
                        "external_link",
                        wagtail.blocks.StructBlock(
                            [
                                ("url", wagtail.blocks.URLBlock()),
                                ("title", wagtail.blocks.CharBlock()),
                            ]
                        ),
                    ),
                    (
                        "internal_link",
                        wagtail.blocks.StructBlock(
                            [
                                ("page", wagtail.blocks.PageChooserBlock()),
                                ("title", wagtail.blocks.CharBlock(required=False)),
                            ]
                        ),
                    ),
                ],
                blank=True,
            ),
        ),
    ]
