# Generated by Django 4.2.11 on 2024-07-09 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0014_toptask"),
        ("utils", "0015_reinstate_search_input_help_text"),
    ]

    operations = []
