# Generated by Django 2.2.19 on 2021-03-15 10:45

from django.db import migrations

import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_campaign_page_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignpage",
            name="sections",
            field=wagtail.fields.StreamField(
                [
                    (
                        "section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        form_classname="full title"
                                    ),
                                ),
                                ("intro", wagtail.blocks.RichTextBlock()),
                            ]
                        ),
                    )
                ],
                null=True,
            ),
        ),
    ]
