# Generated by Django 2.2.19 on 2021-03-15 12:18

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaignpage_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignpage',
            name='sections',
            field=wagtail.core.fields.StreamField([('section', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('intro', wagtail.core.blocks.RichTextBlock(features=['link'])), ('content', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('subheading', wagtail.core.blocks.CharBlock(max_length=250, template='patterns/molecules/streamfield/blocks/subheading_block.html')), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['link']))])))]))], null=True),
        ),
    ]
