# Generated by Django 2.2.19 on 2021-03-23 08:12

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0008_section_content_stream_not_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignpage",
            name="sections",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "section",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.core.blocks.CharBlock(
                                        form_classname="full title",
                                        template="patterns/molecules/streamfield/blocks/heading_block.html",
                                    ),
                                ),
                                (
                                    "intro",
                                    wagtail.core.blocks.RichTextBlock(
                                        features=["link"]
                                    ),
                                ),
                                (
                                    "content",
                                    wagtail.core.blocks.StreamBlock(
                                        [
                                            (
                                                "media_and_paragraph",
                                                wagtail.core.blocks.StructBlock(
                                                    [
                                                        (
                                                            "image_or_embed",
                                                            wagtail.core.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "image",
                                                                        wagtail.images.blocks.ImageChooserBlock(
                                                                            required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "embed",
                                                                        wagtail.embeds.blocks.EmbedBlock(
                                                                            required=False
                                                                        ),
                                                                    ),
                                                                ],
                                                                form_classname="struct-block c-sf-block c-sf-block__content-inner",
                                                            ),
                                                        ),
                                                        (
                                                            "subheading",
                                                            wagtail.core.blocks.CharBlock(
                                                                max_length=250,
                                                                template="patterns/molecules/streamfield/blocks/subheading_block.html",
                                                            ),
                                                        ),
                                                        (
                                                            "paragraph",
                                                            wagtail.core.blocks.RichTextBlock(
                                                                features=["link"]
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "directory_banner",
                                                wagtail.core.blocks.StructBlock(
                                                    [
                                                        (
                                                            "image",
                                                            wagtail.images.blocks.ImageChooserBlock(),
                                                        ),
                                                        (
                                                            "title",
                                                            wagtail.core.blocks.TextBlock(),
                                                        ),
                                                        (
                                                            "description",
                                                            wagtail.core.blocks.TextBlock(),
                                                        ),
                                                        (
                                                            "button",
                                                            wagtail.core.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "text",
                                                                        wagtail.core.blocks.CharBlock(
                                                                            form_classname="title"
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "link_url",
                                                                        wagtail.core.blocks.URLBlock(
                                                                            required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "link_page",
                                                                        wagtail.core.blocks.PageChooserBlock(
                                                                            required=False
                                                                        ),
                                                                    ),
                                                                ],
                                                                form_classname="struct-block c-sf-block c-sf-block__content-inner",
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "full_width_banner",
                                                wagtail.core.blocks.StructBlock(
                                                    [
                                                        (
                                                            "heading",
                                                            wagtail.core.blocks.CharBlock(
                                                                max_length=250
                                                            ),
                                                        ),
                                                        (
                                                            "text",
                                                            wagtail.core.blocks.TextBlock(),
                                                        ),
                                                        (
                                                            "button",
                                                            wagtail.core.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "text",
                                                                        wagtail.core.blocks.CharBlock(
                                                                            form_classname="title"
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "link_url",
                                                                        wagtail.core.blocks.URLBlock(
                                                                            required=False
                                                                        ),
                                                                    ),
                                                                    (
                                                                        "link_page",
                                                                        wagtail.core.blocks.PageChooserBlock(
                                                                            required=False
                                                                        ),
                                                                    ),
                                                                ],
                                                                form_classname="struct-block c-sf-block c-sf-block__content-inner",
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                null=True,
            ),
        ),
    ]
