# Generated by Django 2.2.24 on 2021-07-23 00:05

import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0009_fullwidthbanner_add_heading"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaignpage",
            name="sections",
        ),
        migrations.AddField(
            model_name="campaignpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.blocks.CharBlock(
                            form_classname="full title",
                            group="Text",
                            help_text='3 required. The link to this heading uses the heading text in lowercase, with no symbols, and with the spaces replaced with hyphens. e.g. "Lorem @ 2 ipsum" becomes "lorem-2-ipsum"',
                            icon="title",
                            label="Section heading",
                            template="patterns/molecules/streamfield/blocks/heading_block.html",
                        ),
                    ),
                    (
                        "media_with_subheading_and_paragraph",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image_or_embed",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "image",
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "embed",
                                                wagtail.embeds.blocks.EmbedBlock(
                                                    required=False
                                                ),
                                            ),
                                        ],
                                        form_classname="struct-block c-sf-block c-sf-block__content-inner",
                                    ),
                                ),
                                (
                                    "subheading",
                                    wagtail.blocks.CharBlock(
                                        help_text='The link to this subheading uses the subheading text in lowercase, with no symbols, and with the spaces replaced with hyphens. e.g. "Lorem @ 2 ipsum" becomes "lorem-2-ipsum"',
                                        max_length=250,
                                        template="patterns/molecules/streamfield/blocks/subheading_block.html",
                                    ),
                                ),
                                (
                                    "paragraph",
                                    wagtail.blocks.RichTextBlock(
                                        features=["link", "bold", "italic", "ul", "ol"],
                                        icon="pilcrow",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "directory_banner",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                ("title", wagtail.blocks.TextBlock()),
                                ("description", wagtail.blocks.TextBlock()),
                                (
                                    "button",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "text",
                                                wagtail.blocks.CharBlock(
                                                    form_classname="title"
                                                ),
                                            ),
                                            (
                                                "link_url",
                                                wagtail.blocks.URLBlock(required=False),
                                            ),
                                            (
                                                "link_page",
                                                wagtail.blocks.PageChooserBlock(
                                                    required=False
                                                ),
                                            ),
                                        ],
                                        form_classname="struct-block c-sf-block c-sf-block__content-inner",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "full_width_banner",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(max_length=250),
                                ),
                                ("text", wagtail.blocks.TextBlock()),
                                (
                                    "button",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "text",
                                                wagtail.blocks.CharBlock(
                                                    form_classname="title"
                                                ),
                                            ),
                                            (
                                                "link_url",
                                                wagtail.blocks.URLBlock(required=False),
                                            ),
                                            (
                                                "link_page",
                                                wagtail.blocks.PageChooserBlock(
                                                    required=False
                                                ),
                                            ),
                                        ],
                                        form_classname="struct-block c-sf-block c-sf-block__content-inner",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "subheading_and_paragraph",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "subheading",
                                    wagtail.blocks.CharBlock(
                                        help_text='The link to this subheading uses the subheading text in lowercase, with no symbols, and with the spaces replaced with hyphens. e.g. "Lorem @ 2 ipsum" becomes "lorem-2-ipsum"',
                                        max_length=250,
                                        template="patterns/molecules/streamfield/blocks/subheading_block.html",
                                    ),
                                ),
                                (
                                    "paragraph",
                                    wagtail.blocks.RichTextBlock(
                                        features=["link", "bold", "italic", "ul", "ol"],
                                        icon="pilcrow",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "paragraph",
                        wagtail.blocks.RichTextBlock(
                            features=["link", "bold", "italic", "ul", "ol"],
                            group="Text",
                            icon="pilcrow",
                        ),
                    ),
                    (
                        "media_or_image",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "embed",
                                    wagtail.embeds.blocks.EmbedBlock(required=False),
                                ),
                            ],
                            group="Media",
                            template="patterns/molecules/campaigns/blocks/image-or-media-block.html",
                        ),
                    ),
                ],
                default="",
            ),
            preserve_default=False,
        ),
    ]
