# Generated by Django 4.2.18 on 2025-03-06 07:44

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0012_alter_campaignpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("media_with_subheading_and_paragraph", 6),
                    ("directory_banner", 13),
                    ("full_width_banner", 15),
                    ("subheading_and_paragraph", 16),
                    ("paragraph", 17),
                    ("media_or_image", 18),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "group": "Text",
                            "help_text": '3 required. The link to this heading uses the heading text in lowercase, with no symbols, and with the spaces replaced with hyphens. e.g. "Lorem @ 2 ipsum" becomes "lorem-2-ipsum"',
                            "icon": "title",
                            "label": "Section heading",
                            "template": "patterns/molecules/streamfield/blocks/heading_block.html",
                        },
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    2: ("wagtail.embeds.blocks.EmbedBlock", (), {"required": False}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("embed", 2)]],
                        {
                            "form_classname": "struct-block c-sf-block c-sf-block__content-inner"
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'The link to this subheading uses the subheading text in lowercase, with no symbols, and with the spaces replaced with hyphens. e.g. "Lorem @ 2 ipsum" becomes "lorem-2-ipsum"',
                            "max_length": 250,
                            "template": "patterns/molecules/streamfield/blocks/subheading_block.html",
                        },
                    ),
                    5: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["link", "bold", "italic", "ul", "ol"],
                            "icon": "pilcrow",
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("image_or_embed", 3), ("subheading", 4), ("paragraph", 5)]],
                        {},
                    ),
                    7: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    8: ("wagtail.blocks.TextBlock", (), {}),
                    9: ("wagtail.blocks.CharBlock", (), {"form_classname": "title"}),
                    10: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    11: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 9), ("link_url", 10), ("link_page", 11)]],
                        {
                            "form_classname": "struct-block c-sf-block c-sf-block__content-inner"
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 7),
                                ("title", 8),
                                ("description", 8),
                                ("button", 12),
                            ]
                        ],
                        {},
                    ),
                    14: ("wagtail.blocks.CharBlock", (), {"max_length": 250}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 14), ("text", 8), ("button", 12)]],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("subheading", 4), ("paragraph", 5)]],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["link", "bold", "italic", "ul", "ol"],
                            "group": "Text",
                            "icon": "pilcrow",
                        },
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("embed", 2)]],
                        {
                            "group": "Media",
                            "template": "patterns/molecules/campaigns/blocks/image-or-media-block.html",
                        },
                    ),
                },
            ),
        ),
    ]
