# Generated by Django 2.2.13 on 2020-07-08 16:40

import django.db.models.deletion
from django.db import migrations, models

import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0045_assign_unlock_grouppagepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "content",
                    wagtail.core.fields.RichTextField(blank=True, max_length=255),
                ),
                (
                    "show_on",
                    models.CharField(
                        choices=[
                            ("page only", "the selected page only"),
                            ("descendants", "the selected page and all pages below it"),
                        ],
                        default="descendants",
                        max_length=20,
                        verbose_name="Show on",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="wagtailcore.Page",
                    ),
                ),
            ],
        ),
    ]
