# Generated by Django 3.2.9 on 2022-05-02 07:47

from django.db import migrations

import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_alert_alert_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="content",
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
