# Generated by Django 3.2.13 on 2022-11-09 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0069_log_entry_jsonfield"),
        ("alerts", "0003_alter_alert_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alerts",
                to="wagtailcore.page",
            ),
        ),
    ]
