# Generated by Django 2.2.9 on 2020-01-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_amend_local_area_links_postscript"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventindexpage",
            name="redirect_to",
            field=models.URLField(
                blank=True,
                help_text="Entering a URL here will prevent the page from being visited, and will instead redirect the user.",
                verbose_name="Redirect to external URL",
            ),
        ),
        migrations.AddField(
            model_name="eventpage",
            name="redirect_to",
            field=models.URLField(
                blank=True,
                help_text="Entering a URL here will prevent the page from being visited, and will instead redirect the user.",
                verbose_name="Redirect to external URL",
            ),
        ),
    ]
