# Generated by Django 2.2.10 on 2020-03-31 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_button_block"),
        ("events", "0006_image_block"),
    ]

    operations = []
