# Generated by Django 4.2.14 on 2024-10-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0035_directory_search_block__add_bucks_online_directory_option"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventindexpage",
            name="fetch_all_events",
            field=models.BooleanField(
                default=False,
                help_text="Fetch events from all sites, instead of just displaying child pages of this page",
            ),
            preserve_default=False,
        ),
    ]
