# Generated by Django 2.2.24 on 2021-11-18 11:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_job_employer_logo"),
        ("feedback", "0005_feedback_field_label"),
        ("wagtailredirects", "0006_redirect_increase_max_length"),
        ("wagtailforms", "0004_add_verbose_name_plural"),
        ("forms", "0007_formfield_clean_name"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("wagtailcore", "0062_comment_models_and_pagesubscription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wagtailsearchpromotions", "0002_capitalizeverbose"),
        ("alerts", "0002_alert_alert_level"),
        ("step_by_step", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StepByStepIndexPage",
            new_name="StepByStepPage",
        ),
    ]
