# Generated by Django 2.2.24 on 2021-11-17 16:32

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("step_by_step", "0002_rename_step_by_step_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stepbysteppage",
            name="steps",
            field=wagtail.fields.StreamField(
                [
                    (
                        "step",
                        wagtail.blocks.StructBlock(
                            [
                                ("heading", wagtail.blocks.TextBlock()),
                                ("information", wagtail.blocks.RichTextBlock()),
                            ]
                        ),
                    )
                ]
            ),
        ),
    ]
