# Generated by Django 3.2.9 on 2022-01-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("step_by_step", "0003_add_stepbystep_richtext"),
    ]

    operations = [
        migrations.AddField(
            model_name="stepbysteppage",
            name="intro_text",
            field=models.TextField(blank=True),
        ),
    ]
