# Generated by Django 2.2.24 on 2021-12-01 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0062_comment_models_and_pagesubscription"),
        ("step_by_step", "0003_add_stepbystep_richtext"),
    ]

    operations = [
        migrations.CreateModel(
            name="StepByStepReference",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "referenced_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referenced_step_by_step_pages",
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "step_by_step_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referenced_pages",
                        to="step_by_step.StepByStepPage",
                    ),
                ),
            ],
        ),
    ]
