# Generated by Django 3.2.9 on 2022-05-12 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("step_by_step", "0004_stepbysteppage_intro_text"),
        ("step_by_step", "0004_stepbystepreference"),
    ]

    operations = []
