# Generated by Django 3.2.13 on 2022-08-24 13:49

from django.db import migrations

import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("step_by_step", "0005_merge_20220512_1144"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stepbysteppage",
            name="steps",
            field=wagtail.fields.StreamField(
                [
                    (
                        "step",
                        wagtail.blocks.StructBlock(
                            [
                                ("heading", wagtail.blocks.TextBlock()),
                                ("information", wagtail.blocks.RichTextBlock()),
                            ]
                        ),
                    )
                ],
                use_json_field=True,
            ),
        ),
    ]
